"""
FINN3021 — Interactive Portfolio Dashboard
==========================================
Run:  python dashboard/app.py
Open:  http://127.0.0.1:8050

Reads holdings from data/outputs/portfolio_snapshot.csv (generated by
02_portfolio_dashboard.ipynb).  Pulls live prices via yfinance on each
page load.  Re-run the notebook → refresh the browser to pick up changes.
"""

import os
import pathlib
from datetime import date

import dash
import dash_bootstrap_components as dbc
import numpy as np
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
import yfinance as yf
from dash import Input, Output, callback, dash_table, dcc, html
from scipy import stats as sp_stats

# ── Paths ─────────────────────────────────────────────────────────
ROOT = pathlib.Path(__file__).resolve().parent.parent
DATA = ROOT / "data" / "outputs"

# ── Constants (must match the notebook) ───────────────────────────
INCEPTION = date(2026, 3, 9)
BENCHMARK = "ACWX"
RISK_FREE_ANNUAL = 0.043
NOTIONAL = 1_000_000
HORIZON_YRS = 10

COUNTRY_NAMES = {
    "JP": "Japan", "ZA": "South Africa", "IN": "India",
    "GB": "United Kingdom", "QA": "Qatar", "US": "United States",
    "BR": "Brazil", "TW": "Taiwan", "ID": "Indonesia",
    "MX": "Mexico", "IT": "Italy", "CH": "Switzerland",
    "DE": "Germany", "TH": "Thailand", "SA": "Saudi Arabia",
    "FR": "France",
}

# ── Load data from notebook CSVs ─────────────────────────────────

def load_snapshot():
    """Read the latest portfolio_snapshot.csv."""
    return pd.read_csv(DATA / "portfolio_snapshot.csv")


def load_fundamentals():
    """Load screen-level fundamentals for holdings."""
    screen = pd.read_csv(DATA / "portfolio_screen_final20.csv")
    snap = load_snapshot()
    # Build name→ticker map from snapshot (only names present in screen CSV)
    name_map = {
        "AUTOTRADER GROUP PLC":          "AUTO.L",
        "KAKAKU.COM INC":                "2371.T",
        "CLICKS GROUP LTD":              "CLS.JO",
        "ITC LTD":                       "ITC.NS",
        "ODONTOPREV SA":                 "ODPV3.SA",
        "NEXT PLC":                      "NXT.L",
        "CROMPTON GREAVES CONSUMER":     "CROMPTON.NS",
        "RECRUIT HOLDINGS CO LTD":       "6098.T",
        "HANJAYA MANDALA SAMPOERNA":     "HMSP.JK",
        "KIMBERLY-CLARK DE MEXICO SA":   "KIMBERA.MX",
        "MR PRICE GROUP LTD":            "MRP.JO",
        "MARUWA CO LTD":                 "5344.T",
        "DORMAKABA HOLDINGS AG":         "DOKA.SW",
        "BUMRUNGRAD HOSPITAL PCL":       "BH.BK",
    }
    screen["ticker"] = screen["company_name"].map(name_map)
    matched = screen[screen["ticker"].isin(snap["ticker"])].copy()
    cols = [c for c in ["ticker", "rk", "piotroski", "roic_5y_avg",
                        "fcf_ev_5y_avg", "div_yield", "pe_ratio",
                        "net_debt_ebitda", "altman_z", "composite",
                        "fcf_growth_5y", "driver"] if c in matched.columns]
    return matched[cols].set_index("ticker")


def pull_live_prices(tickers):
    """Pull adjusted close prices from yfinance since inception."""
    start = (pd.Timestamp(INCEPTION) - pd.Timedelta(days=5)).strftime("%Y-%m-%d")
    raw = yf.download(tickers, start=start, auto_adjust=True, progress=False)
    if isinstance(raw.columns, pd.MultiIndex):
        prices = raw["Close"].copy()
    else:
        prices = raw[["Close"]].copy()
        prices.columns = tickers
    prices = prices.ffill()
    prices = prices[prices.index >= pd.Timestamp(INCEPTION)]
    return prices


def compute_all():
    """Compute every metric from live prices + snapshot CSVs."""
    snap = load_snapshot()
    eq_tickers = snap["ticker"].tolist()
    all_tickers = eq_tickers + [BENCHMARK]
    prices = pull_live_prices(all_tickers)

    # Shares & cost from snapshot
    positions = snap.copy()

    shares = positions.set_index("ticker")["shares"]

    # Daily values — 100% equity
    eq_values = prices[eq_tickers].multiply(shares, axis=1)
    port_value = eq_values.sum(axis=1)

    port_return = port_value / port_value.iloc[0] - 1
    bench_return = prices[BENCHMARK] / prices[BENCHMARK].iloc[0] - 1

    # Daily returns
    port_daily = port_value.pct_change().dropna()
    bench_daily = prices[BENCHMARK].pct_change().dropna()
    aligned = pd.DataFrame({"port": port_daily, "bench": bench_daily}).dropna()

    # Per-stock returns
    stock_ret = prices[eq_tickers] / prices[eq_tickers].iloc[0] - 1

    # Latest P&L
    latest = prices[eq_tickers].iloc[-1]
    pos_pnl = positions.copy()
    pos_pnl["current_px"] = pos_pnl["ticker"].map(latest)
    pos_pnl["current_value"] = pos_pnl["shares"] * pos_pnl["current_px"]
    pos_pnl["pnl"] = pos_pnl["current_value"] - pos_pnl["cost_basis"]
    pos_pnl["return_pct"] = pos_pnl["pnl"] / pos_pnl["cost_basis"] * 100
    pos_pnl["weight_now"] = pos_pnl["current_value"] / port_value.iloc[-1] * 100
    pos_pnl["country_name"] = pos_pnl["country"].map(COUNTRY_NAMES)

    # Risk metrics
    ann = 252
    rf_d = (1 + RISK_FREE_ANNUAL) ** (1 / 252) - 1
    p_ann_ret = (1 + aligned["port"].mean()) ** ann - 1
    b_ann_ret = (1 + aligned["bench"].mean()) ** ann - 1
    p_ann_vol = aligned["port"].std() * np.sqrt(ann)
    b_ann_vol = aligned["bench"].std() * np.sqrt(ann)
    excess = aligned["port"] - rf_d
    active = aligned["port"] - aligned["bench"]
    sharpe = excess.mean() / aligned["port"].std() * np.sqrt(ann) if aligned["port"].std() > 0 else 0
    te = active.std() * np.sqrt(ann)
    ir = active.mean() / active.std() * np.sqrt(ann) if active.std() > 0 else 0
    cov_m = np.cov(aligned["port"], aligned["bench"])
    beta = cov_m[0, 1] / cov_m[1, 1] if cov_m[1, 1] > 0 else 0
    treynor = (p_ann_ret - RISK_FREE_ANNUAL) / beta if beta != 0 else 0
    reg = sp_stats.linregress(aligned["bench"], aligned["port"])
    alpha_ann = reg.intercept * ann
    r2 = reg.rvalue ** 2
    dd_port = (port_value - port_value.cummax()) / port_value.cummax()
    dd_bench = (prices[BENCHMARK] - prices[BENCHMARK].cummax()) / prices[BENCHMARK].cummax()
    down = aligned["port"][aligned["port"] < 0]
    down_vol = down.std() * np.sqrt(ann) if len(down) > 0 else 0
    sortino = (p_ann_ret - RISK_FREE_ANNUAL) / down_vol if down_vol > 0 else 0
    max_dd = abs(dd_port.min())
    calmar = (p_ann_ret - RISK_FREE_ANNUAL) / max_dd if max_dd > 0 else 0
    up_d = aligned[aligned["bench"] > 0]
    dn_d = aligned[aligned["bench"] < 0]
    up_cap = up_d["port"].mean() / up_d["bench"].mean() * 100 if len(up_d) > 0 else 0
    dn_cap = dn_d["port"].mean() / dn_d["bench"].mean() * 100 if len(dn_d) > 0 else 0

    p_daily_std = aligned["port"].std()
    b_daily_std = aligned["bench"].std()

    # Benchmark equivalents
    b_excess = aligned["bench"] - rf_d
    b_sharpe = b_excess.mean() / aligned["bench"].std() * np.sqrt(ann) if aligned["bench"].std() > 0 else 0
    b_down = aligned["bench"][aligned["bench"] < 0]
    b_down_vol = b_down.std() * np.sqrt(ann) if len(b_down) > 0 else 0
    b_sortino = (b_ann_ret - RISK_FREE_ANNUAL) / b_down_vol if b_down_vol > 0 else 0
    b_treynor = (b_ann_ret - RISK_FREE_ANNUAL) / 1.0  # benchmark beta = 1
    b_max_dd = abs(dd_bench.min())
    b_calmar = (b_ann_ret - RISK_FREE_ANNUAL) / b_max_dd if b_max_dd > 0 else 0

    risk = {
        "Ann. Return": f"{p_ann_ret:.2%}", "Ann. Vol": f"{p_ann_vol:.2%}",
        "Daily Std Dev": f"{p_daily_std:.4%}",
        "Sharpe": f"{sharpe:.2f}", "Sortino": f"{sortino:.2f}",
        "Treynor": f"{treynor:.4f}", "Calmar": f"{calmar:.2f}",
        "Info Ratio": f"{ir:.2f}", "Tracking Error": f"{te:.2%}",
        "Beta": f"{beta:.3f}", "Alpha (ann)": f"{alpha_ann:.2%}",
        "R²": f"{r2:.3f}", "Max DD": f"{dd_port.min():.2%}",
        "Downside Vol": f"{down_vol:.2%}",
        "Up Capture": f"{up_cap:.1f}%", "Down Capture": f"{dn_cap:.1f}%",
    }
    bench_risk = {
        "Ann. Return": f"{b_ann_ret:.2%}", "Ann. Vol": f"{b_ann_vol:.2%}",
        "Daily Std Dev": f"{b_daily_std:.4%}",
        "Sharpe": f"{b_sharpe:.2f}", "Sortino": f"{b_sortino:.2f}",
        "Treynor": f"{b_treynor:.4f}", "Calmar": f"{b_calmar:.2f}",
        "Info Ratio": "—", "Tracking Error": "—",
        "Beta": "1.000", "Alpha (ann)": "0.00%",
        "R²": "1.000", "Max DD": f"{dd_bench.min():.2%}",
        "Downside Vol": f"{b_down_vol:.2%}",
        "Up Capture": "100.0%", "Down Capture": "100.0%",
    }
    risk_df = pd.DataFrame({
        "Metric": list(risk.keys()),
        "Portfolio": list(risk.values()),
        "Benchmark": list(bench_risk.values()),
    })

    # Correlation
    eq_dr = prices[eq_tickers].pct_change().dropna()
    name_map = positions.set_index("ticker")["name"]
    eq_dr.columns = [name_map.get(t, t) for t in eq_tickers]
    corr = eq_dr.corr()

    return {
        "prices": prices,
        "port_return": port_return,
        "bench_return": bench_return,
        "port_value": port_value,
        "pos_pnl": pos_pnl,
        "stock_ret": stock_ret,
        "dd_port": dd_port,
        "dd_bench": dd_bench,
        "risk_df": risk_df,
        "corr": corr,
        "aligned": aligned,
        "reg": reg,
        "beta": beta,
        "alpha_ann": alpha_ann,
        "r2": r2,
        "sharpe": sharpe,
        "p_ann_ret": p_ann_ret,
        "p_ann_vol": p_ann_vol,
        "max_dd_val": dd_port.min(),
        "ir": ir,
        "name_map": name_map,
    }


# ── Dash app ──────────────────────────────────────────────────────
app = dash.Dash(
    __name__,
    external_stylesheets=[dbc.themes.DARKLY],
    title="FINN3021 Portfolio Dashboard",
    suppress_callback_exceptions=True,
)
server = app.server  # expose for gunicorn


def kpi_card(title, value, sub=None, color="primary"):
    """Small KPI card component."""
    body = [html.H4(value, className="card-title mb-0",
                     style={"fontWeight": "700", "fontSize": "1.6rem"})]
    if sub:
        body.append(html.P(sub, className="card-text text-muted mb-0",
                           style={"fontSize": "0.75rem"}))
    return dbc.Card(
        dbc.CardBody([
            html.P(title, className="text-muted mb-1",
                   style={"fontSize": "0.75rem", "textTransform": "uppercase",
                           "letterSpacing": "1px"}),
            *body,
        ]),
        className=f"border-{color}",
        style={"borderLeft": "4px solid", "backgroundColor": "#1a1a2e"},
    )


def build_layout():
    return dbc.Container([
        # ── Header ───────────────────────────────────────────────
        dbc.Row(dbc.Col(html.Div([
            html.H2("FINN3021 — Portfolio Dashboard",
                     className="mb-0", style={"fontWeight": "800"}),
            html.P(
                f"Inception {INCEPTION}  ·  100% equity (conviction-weighted)  ·  "
                f"Benchmark: {BENCHMARK}  ·  Live prices via yfinance",
                className="text-muted mb-0", style={"fontSize": "0.85rem"}),
        ]), width=12), className="my-3"),

        # Refresh button + last-update
        dbc.Row([
            dbc.Col(dbc.Button("↻  Refresh data", id="refresh-btn",
                               color="info", size="sm", className="me-2"),
                    width="auto"),
            dbc.Col(html.Span(id="last-update", className="text-muted",
                              style={"fontSize": "0.8rem"}), width="auto"),
        ], className="mb-3", align="center"),

        # Placeholder for dynamic content
        html.Div(id="dashboard-content"),

        # ── Footer ───────────────────────────────────────────────
        html.Hr(),
        html.P("Data: yfinance · Screen: WRDS Compustat Global · Not investment advice",
               className="text-muted text-center", style={"fontSize": "0.7rem"}),
    ], fluid=True, style={"backgroundColor": "#0f0f23", "minHeight": "100vh",
                           "padding": "20px 30px"})


app.layout = build_layout


@callback(
    Output("dashboard-content", "children"),
    Output("last-update", "children"),
    Input("refresh-btn", "n_clicks"),
)
def refresh_dashboard(_):
    """Rebuild the entire dashboard from live data."""
    d = compute_all()
    pos = d["pos_pnl"]
    last_date = d["prices"].index[-1].strftime("%d %b %Y %H:%M")
    total_ret = d["port_return"].iloc[-1]
    bench_ret = d["bench_return"].iloc[-1]
    active_ret = total_ret - bench_ret

    # Load fundamentals
    try:
        fundas = load_fundamentals()
    except Exception:
        fundas = pd.DataFrame()

    # ── KPI Cards ────────────────────────────────────────────
    ret_color = "success" if total_ret >= 0 else "danger"
    act_color = "success" if active_ret >= 0 else "danger"
    kpis = dbc.Row([
        dbc.Col(kpi_card("Portfolio Value",
                         f"${d['port_value'].iloc[-1]:,.0f}",
                         f"from $1,000,000", "info"), md=2),
        dbc.Col(kpi_card("Total Return",
                         f"{total_ret:+.2%}", "since inception", ret_color), md=2),
        dbc.Col(kpi_card("Active Return",
                         f"{active_ret:+.2%}", f"vs {BENCHMARK}", act_color), md=2),
        dbc.Col(kpi_card("Ann. Volatility",
                         f"{d['p_ann_vol']:.2%}", "std dev (ann.)", "warning"), md=2),
        dbc.Col(kpi_card("Sharpe Ratio",
                         f"{d['sharpe']:.2f}", "annualised", "warning"), md=2),
        dbc.Col(kpi_card("Max Drawdown",
                         f"{d['max_dd_val']:.2%}", "from peak", "danger"), md=2),
    ], className="mb-4 g-3")

    # ── Performance chart ────────────────────────────────────
    perf_fig = go.Figure()
    perf_fig.add_trace(go.Scatter(
        x=d["port_return"].index, y=d["port_return"] * 100,
        name="Portfolio", line=dict(color="#00d4ff", width=2.5),
    ))
    perf_fig.add_trace(go.Scatter(
        x=d["bench_return"].index, y=d["bench_return"] * 100,
        name=f"Benchmark ({BENCHMARK})",
        line=dict(color="#ff6b6b", width=2, dash="dash"),
    ))
    perf_fig.add_trace(go.Scatter(
        x=d["port_return"].index,
        y=(d["port_return"] - d["bench_return"]) * 100,
        name="Active return", fill="tozeroy",
        line=dict(color="rgba(0,180,100,0.4)", width=0),
        fillcolor="rgba(0,180,100,0.15)",
    ))
    perf_fig.update_layout(
        title="Cumulative Return — Portfolio vs Benchmark",
        template="plotly_dark", paper_bgcolor="#0f0f23",
        plot_bgcolor="#1a1a2e", yaxis_title="Return (%)",
        legend=dict(orientation="h", y=1.12),
        height=420, margin=dict(l=50, r=20, t=60, b=40),
        hovermode="x unified",
    )

    # ── Drawdown chart ───────────────────────────────────────
    dd_fig = go.Figure()
    dd_fig.add_trace(go.Scatter(
        x=d["dd_port"].index, y=d["dd_port"] * 100,
        name="Portfolio", fill="tozeroy",
        line=dict(color="#ff6b6b", width=1.5),
        fillcolor="rgba(255,50,50,0.3)",
    ))
    dd_fig.add_trace(go.Scatter(
        x=d["dd_bench"].index, y=d["dd_bench"] * 100,
        name="Benchmark", line=dict(color="#ffa500", width=1, dash="dot"),
    ))
    dd_fig.update_layout(
        title="Drawdown from Peak",
        template="plotly_dark", paper_bgcolor="#0f0f23",
        plot_bgcolor="#1a1a2e", yaxis_title="Drawdown (%)",
        legend=dict(orientation="h", y=1.12),
        height=300, margin=dict(l=50, r=20, t=60, b=40),
        hovermode="x unified",
    )

    # ── Country & sector pies ────────────────────────────────
    ctry = pos.groupby("country_name")["current_value"].sum().reset_index()
    sec = pos.groupby("sector")["current_value"].sum().reset_index()
    ctry_fig = px.pie(
        ctry, values="current_value", names="country_name",
        hole=0.45, color_discrete_sequence=px.colors.qualitative.Set2,
    )
    ctry_fig.update_layout(
        title="Country Exposure", template="plotly_dark",
        paper_bgcolor="#0f0f23", height=370,
        margin=dict(l=10, r=10, t=50, b=10),
        legend=dict(font=dict(size=10)),
    )
    sec_fig = px.pie(
        sec, values="current_value", names="sector",
        hole=0.45, color_discrete_sequence=px.colors.qualitative.Pastel,
    )
    sec_fig.update_layout(
        title="Sector Exposure", template="plotly_dark",
        paper_bgcolor="#0f0f23", height=370,
        margin=dict(l=10, r=10, t=50, b=10),
        legend=dict(font=dict(size=10)),
    )

    # ── Positions table ──────────────────────────────────────
    tbl = pos[["name", "ticker", "country", "sector",
               "inception_px", "current_px", "pnl", "return_pct",
               "weight_now"]].copy()
    tbl.columns = ["Name", "Ticker", "Country", "Sector",
                   "Entry Px", "Current Px", "P&L ($)", "Return %", "Weight %"]
    for c in ["Entry Px", "Current Px"]:
        tbl[c] = tbl[c].round(2)
    tbl["P&L ($)"] = tbl["P&L ($)"].round(0)
    tbl["Return %"] = tbl["Return %"].round(2)
    tbl["Weight %"] = tbl["Weight %"].round(2)
    tbl = tbl.sort_values("Return %", ascending=False)

    pos_table = dash_table.DataTable(
        data=tbl.to_dict("records"),
        columns=[{"name": c, "id": c} for c in tbl.columns],
        sort_action="native",
        style_table={"overflowX": "auto"},
        style_header={
            "backgroundColor": "#16213e", "color": "#e0e0e0",
            "fontWeight": "bold", "fontSize": "0.8rem",
            "borderBottom": "2px solid #00d4ff",
        },
        style_cell={
            "backgroundColor": "#1a1a2e", "color": "#e0e0e0",
            "fontSize": "0.8rem", "padding": "8px 12px",
            "border": "1px solid #2a2a4a",
        },
        style_data_conditional=[
            {"if": {"filter_query": "{Return %} > 0", "column_id": "Return %"},
             "color": "#00e676", "fontWeight": "bold"},
            {"if": {"filter_query": "{Return %} < 0", "column_id": "Return %"},
             "color": "#ff5252", "fontWeight": "bold"},
            {"if": {"filter_query": "{P&L ($)} > 0", "column_id": "P&L ($)"},
             "color": "#00e676"},
            {"if": {"filter_query": "{P&L ($)} < 0", "column_id": "P&L ($)"},
             "color": "#ff5252"},
            {"if": {"state": "active"}, "backgroundColor": "#212145",
             "border": "1px solid #00d4ff"},
        ],
        page_size=25,
    )

    # ── Correlation heatmap ──────────────────────────────────
    corr = d["corr"]
    # Mask upper triangle
    mask = np.triu(np.ones_like(corr, dtype=bool), k=0)
    corr_masked = corr.where(~mask)

    corr_fig = go.Figure(data=go.Heatmap(
        z=corr.values, x=corr.columns, y=corr.index,
        colorscale="RdYlGn_r", zmin=-1, zmax=1,
        text=corr.round(2).values,
        texttemplate="%{text:.2f}",
        textfont={"size": 8},
        hovertemplate="%{x} vs %{y}: %{z:.3f}<extra></extra>",
    ))
    corr_fig.update_layout(
        title=f"Pairwise Correlation  ·  avg = {corr.where(~np.eye(len(corr), dtype=bool)).stack().mean():.3f}",
        template="plotly_dark", paper_bgcolor="#0f0f23",
        plot_bgcolor="#1a1a2e", height=550,
        margin=dict(l=120, r=20, t=60, b=120),
        xaxis=dict(tickangle=45, tickfont=dict(size=9)),
        yaxis=dict(tickfont=dict(size=9)),
    )

    # ── CAPM regression ──────────────────────────────────────
    al = d["aligned"]
    capm_fig = go.Figure()
    capm_fig.add_trace(go.Scatter(
        x=al["bench"] * 100, y=al["port"] * 100,
        mode="markers", name="Daily returns",
        marker=dict(color="#00d4ff", size=6, opacity=0.5),
    ))
    x_line = np.linspace(al["bench"].min(), al["bench"].max(), 100)
    y_line = d["reg"].intercept + d["reg"].slope * x_line
    capm_fig.add_trace(go.Scatter(
        x=x_line * 100, y=y_line * 100,
        mode="lines", name=f"α={d['alpha_ann']:.2%} β={d['beta']:.3f} R²={d['r2']:.3f}",
        line=dict(color="#ff6b6b", width=2),
    ))
    lim = max(abs(al["bench"].min()), abs(al["bench"].max())) * 100
    capm_fig.add_trace(go.Scatter(
        x=[-lim, lim], y=[-lim, lim], mode="lines", name="β=1",
        line=dict(color="grey", width=1, dash="dot"),
    ))
    capm_fig.update_layout(
        title="CAPM Regression — Portfolio vs Benchmark",
        template="plotly_dark", paper_bgcolor="#0f0f23",
        plot_bgcolor="#1a1a2e",
        xaxis_title=f"Benchmark daily return (%) — {BENCHMARK}",
        yaxis_title="Portfolio daily return (%)",
        height=420, margin=dict(l=50, r=20, t=60, b=50),
        legend=dict(orientation="h", y=-0.18, font=dict(size=10)),
    )

    # ── Risk metrics table ───────────────────────────────────
    risk_table = dash_table.DataTable(
        data=d["risk_df"].to_dict("records"),
        columns=[{"name": c, "id": c} for c in d["risk_df"].columns],
        style_header={
            "backgroundColor": "#16213e", "color": "#e0e0e0",
            "fontWeight": "bold", "fontSize": "0.82rem",
            "borderBottom": "2px solid #ffa500",
        },
        style_cell={
            "backgroundColor": "#1a1a2e", "color": "#e0e0e0",
            "fontSize": "0.82rem", "padding": "6px 14px",
            "border": "1px solid #2a2a4a",
        },
    )

    # ── Fundamentals table ───────────────────────────────────
    fund_section = html.Div()
    if not fundas.empty:
        fd = fundas.reset_index().merge(
            pos[["ticker", "name", "return_pct"]], on="ticker", how="left"
        )
        for c in ["roic_5y_avg", "fcf_ev_5y_avg", "div_yield", "fcf_growth_5y"]:
            if c in fd.columns:
                fd[c] = (fd[c] * 100).round(1)
        for c in ["composite", "net_debt_ebitda", "altman_z"]:
            if c in fd.columns:
                fd[c] = fd[c].round(2)
        if "pe_ratio" in fd.columns:
            fd["pe_ratio"] = fd["pe_ratio"].round(1)
        fd["return_pct"] = fd["return_pct"].round(1)

        # Pull market cap & daily volume from yfinance (convert to USD)
        # Fetch FX rates once for all needed currencies
        fx_cache = {}
        # yfinance reports currency as minor unit (ZAc, GBp) for some exchanges
        # but marketCap is already in the major unit (ZAR, GBP). Map to major.
        _MINOR_TO_MAJOR = {"ZAC": "ZAR", "GBP": "GBP"}  # GBp→GBP, ZAc→ZAR
        def _to_usd(value, ccy):
            if value is None or ccy is None:
                return None
            ccy = ccy.upper()
            if ccy == "USD":
                return value
            # Map minor-unit label to major currency (no division —
            # marketCap is already in the major unit)
            ccy = _MINOR_TO_MAJOR.get(ccy, ccy)
            if ccy not in fx_cache:
                pair = f"{ccy}USD=X"
                try:
                    rate_data = yf.Ticker(pair).history(period="1d")
                    fx_cache[ccy] = rate_data["Close"].iloc[-1] if len(rate_data) else None
                except Exception:
                    fx_cache[ccy] = None
            rate = fx_cache.get(ccy)
            return value * rate if rate else None

        mcaps, vols = [], []
        for t in fd["ticker"]:
            try:
                info = yf.Ticker(t).info
                mc = info.get("marketCap")
                ccy = info.get("currency", "USD")
                # Convert local-currency market cap to USD
                mc_usd = _to_usd(mc, ccy) if mc else None
                mcaps.append(round(mc_usd / 1e9, 2) if mc_usd else None)
                vl = info.get("averageDailyVolume10Day") or info.get("volume")
                vols.append(int(vl) if vl else None)
            except Exception:
                mcaps.append(None)
                vols.append(None)
        fd["mkt_cap_bn"] = mcaps
        fd["avg_daily_vol"] = vols

        fd = fd.sort_values("composite", ascending=False)
        show_cols = ["name", "return_pct", "composite", "piotroski",
                     "roic_5y_avg", "fcf_ev_5y_avg", "div_yield",
                     "pe_ratio", "net_debt_ebitda", "mkt_cap_bn",
                     "avg_daily_vol"]
        show_cols = [c for c in show_cols if c in fd.columns]
        nice = {"name": "Name", "return_pct": "Ret %", "composite": "Composite",
                "piotroski": "Piotroski", "roic_5y_avg": "ROIC %",
                "fcf_ev_5y_avg": "FCF/EV %", "div_yield": "Div Yield %",
                "pe_ratio": "P/E", "net_debt_ebitda": "ND/EBITDA",
                "mkt_cap_bn": "Mkt Cap ($B)", "avg_daily_vol": "Avg Daily Vol"}

        # Append average row
        avg_row = {"name": "AVERAGE"}
        num_cols = [c for c in show_cols if c != "name"]
        for c in num_cols:
            avg_row[c] = fd[c].mean() if fd[c].notna().any() else None
            if avg_row[c] is not None:
                if c == "avg_daily_vol":
                    avg_row[c] = int(round(avg_row[c]))
                elif c == "piotroski":
                    avg_row[c] = round(avg_row[c], 1)
                else:
                    avg_row[c] = round(avg_row[c], 2) if isinstance(avg_row[c], float) else avg_row[c]
        fd_display = pd.concat([fd[show_cols], pd.DataFrame([avg_row])], ignore_index=True)

        fund_table = dash_table.DataTable(
            data=fd_display.to_dict("records"),
            columns=[{"name": nice.get(c, c), "id": c} for c in show_cols],
            sort_action="native",
            style_header={
                "backgroundColor": "#16213e", "color": "#e0e0e0",
                "fontWeight": "bold", "fontSize": "0.8rem",
                "borderBottom": "2px solid #9c27b0",
            },
            style_cell={
                "backgroundColor": "#1a1a2e", "color": "#e0e0e0",
                "fontSize": "0.8rem", "padding": "6px 12px",
                "border": "1px solid #2a2a4a",
            },
            style_data_conditional=[
                {"if": {"filter_query": '{name} = "AVERAGE"'},
                 "backgroundColor": "#16213e", "fontWeight": "bold",
                 "borderTop": "2px solid #9c27b0"},
            ],
        )
        fund_section = html.Div([
            html.H5("Screen Fundamentals", className="text-light mt-4 mb-2"),
            fund_table,
        ])

    # ── Per-stock sparklines ─────────────────────────────────
    stock_fig = go.Figure()
    names = d["name_map"]
    for t in pos["ticker"]:
        sr = d["stock_ret"][t] * 100
        stock_fig.add_trace(go.Scatter(
            x=sr.index, y=sr,
            name=names.get(t, t),
            mode="lines", line=dict(width=1.5),
            hovertemplate=f"{names.get(t, t)}: " + "%{y:.2f}%<extra></extra>",
        ))
    stock_fig.update_layout(
        title="Individual Stock Returns Since Inception",
        template="plotly_dark", paper_bgcolor="#0f0f23",
        plot_bgcolor="#1a1a2e", yaxis_title="Return (%)",
        height=450, margin=dict(l=50, r=20, t=60, b=40),
        legend=dict(font=dict(size=9)),
        hovermode="x unified",
    )

    # ── Total shareholder yield analysis ─────────────────────
    def _safe_yield(info):
        """Return (trailing, forward) yields as decimals (0.02 = 2%)."""
        raw_fwd = info.get("dividendYield")
        fwd = raw_fwd / 100 if raw_fwd is not None else None
        raw_trail = info.get("trailingAnnualDividendYield")
        if raw_trail is not None and raw_trail > 0:
            ccy = (info.get("currency") or "")
            is_minor = len(ccy) == 3 and ccy[-1].islower()
            trail = raw_trail * 100 if is_minor else raw_trail
        else:
            trail = fwd
        return trail, fwd

    def _buyback_yield(ticker_obj, info):
        """Net buyback yield from most recent annual cash-flow statement."""
        try:
            cf = ticker_obj.cashflow
            mktcap = info.get("marketCap")
            if cf is None or cf.empty or not mktcap or mktcap <= 0:
                return None
            repurchase = 0
            if "Repurchase Of Capital Stock" in cf.index:
                v = cf.loc["Repurchase Of Capital Stock"].dropna()
                if len(v) > 0:
                    repurchase = float(v.iloc[0])
            issuance = 0
            if "Issuance Of Capital Stock" in cf.index:
                v = cf.loc["Issuance Of Capital Stock"].dropna()
                if len(v) > 0:
                    issuance = float(v.iloc[0])
            net_buyback = -(repurchase + issuance)
            return net_buyback / mktcap
        except Exception:
            return None

    def _norm_payout(v):
        if v is None:
            return None
        try:
            v = float(v)
        except (TypeError, ValueError):
            return None
        if np.isnan(v):
            return None
        return v / 100 if v > 1 else v

    div_data = []
    for _, h in pos.iterrows():
        try:
            tk = yf.Ticker(h["ticker"])
            info = tk.info
            trail_y, fwd_y = _safe_yield(info)
            payout  = _norm_payout(info.get("payoutRatio"))
            bb_y    = _buyback_yield(tk, info)
        except Exception:
            trail_y = fwd_y = payout = bb_y = None
        fwd_pct   = round(fwd_y * 100, 2)   if fwd_y   else None
        bb_pct    = round(bb_y * 100, 2)     if bb_y is not None else None
        total_sh  = round((fwd_pct or 0) + (bb_pct or 0), 2)
        div_data.append({
            "Name":            h["name"],
            "Country":         h["country"],
            "Trailing Yield %": round(trail_y * 100, 2) if trail_y else None,
            "Forward Yield %":  fwd_pct,
            "Buyback Yield %":  bb_pct,
            "Total SH Yield %": total_sh,
            "Payout Ratio %":   round(payout * 100, 1)   if payout  else None,
            "Current Value":    round(h["current_value"], 0),
        })
    div_df = pd.DataFrame(div_data)

    # Estimated annual income per holding (dividends only)
    div_df["Est. Ann. Income"] = (
        div_df["Current Value"] * div_df["Forward Yield %"].fillna(div_df["Trailing Yield %"]).fillna(0) / 100
    ).round(0)

    # Portfolio-level summary
    total_eq_value = div_df["Current Value"].sum()
    total_income = div_df["Est. Ann. Income"].sum()
    port_avg_yield = (total_income / total_eq_value * 100) if total_eq_value > 0 else 0
    # Weighted buyback yield
    div_df["_wt"] = div_df["Current Value"] / total_eq_value if total_eq_value > 0 else 0
    port_bb_yield = (div_df["Buyback Yield %"].fillna(0) * div_df["_wt"]).sum()
    port_total_sh_yield = port_avg_yield + port_bb_yield
    div_df.drop(columns=["_wt"], inplace=True)

    price_only_ret = total_ret
    # Annualised total return estimate including total shareholder yield
    days_held = (d["prices"].index[-1] - d["prices"].index[0]).days
    ann_sh_boost = port_total_sh_yield / 100  # div + buyback yield
    price_ann = (1 + price_only_ret) ** (365 / max(days_held, 1)) - 1
    total_ret_with_div = price_ann + ann_sh_boost  # includes buybacks

    # ── Dividend reinvestment projection chart ───────────
    # Project forward from inception: price-only NAV vs total return NAV
    # using actual price history + daily accrual of total shareholder yield
    daily_yield = port_total_sh_yield / 100 / 252  # daily TSY accrual
    price_nav = d["port_value"] / d["port_value"].iloc[0] * NOTIONAL
    # Build total-return NAV: reinvest dividends daily
    tr_nav = [NOTIONAL]
    for i in range(1, len(d["port_value"])):
        price_change = d["port_value"].iloc[i] / d["port_value"].iloc[i - 1]
        tr_nav.append(tr_nav[-1] * price_change * (1 + daily_yield))
    tr_nav = pd.Series(tr_nav, index=d["port_value"].index)

    # Also project 10-year forward from inception
    proj_years = np.arange(0, HORIZON_YRS + 1)
    price_only_proj = NOTIONAL * (1 + price_ann) ** proj_years
    total_ret_proj = NOTIONAL * (1 + total_ret_with_div) ** proj_years
    proj_labels = [f"Yr {y}" for y in proj_years]

    reinvest_fig = go.Figure()
    # Actual period
    reinvest_fig.add_trace(go.Scatter(
        x=price_nav.index, y=price_nav,
        name="Price-only NAV", line=dict(color="#ff6b6b", width=2),
    ))
    reinvest_fig.add_trace(go.Scatter(
        x=tr_nav.index, y=tr_nav,
        name="Total return NAV (TSY reinvested)",
        line=dict(color="#00e676", width=2.5),
        fill="tonexty", fillcolor="rgba(0,230,118,0.1)",
    ))
    reinvest_fig.update_layout(
        title=f"Total Shareholder Yield Impact — Actual Period  (TSY {port_total_sh_yield:.1f}%)",
        template="plotly_dark", paper_bgcolor="#0f0f23",
        plot_bgcolor="#1a1a2e", yaxis_title="NAV ($)",
        height=350, margin=dict(l=60, r=20, t=60, b=40),
        legend=dict(orientation="h", y=1.12),
        hovermode="x unified",
        yaxis=dict(tickprefix="$", tickformat=",.0f"),
    )

    # 10-year projection
    proj_fig = go.Figure()
    proj_fig.add_trace(go.Bar(
        x=proj_labels, y=price_only_proj,
        name=f"Price only ({price_ann:.1%} p.a.)",
        marker_color="#ff6b6b", opacity=0.7,
    ))
    proj_fig.add_trace(go.Bar(
        x=proj_labels, y=total_ret_proj,
        name=f"With TSY reinvested ({total_ret_with_div:.1%} p.a.)",
        marker_color="#00e676", opacity=0.7,
    ))
    yr10_diff = total_ret_proj[-1] - price_only_proj[-1]
    proj_fig.update_layout(
        title=f"10-Year Projection — Total Shareholder Yield Adds ${yr10_diff:,.0f}",
        template="plotly_dark", paper_bgcolor="#0f0f23",
        plot_bgcolor="#1a1a2e", yaxis_title="NAV ($)",
        barmode="group", height=350,
        margin=dict(l=60, r=20, t=60, b=40),
        legend=dict(orientation="h", y=1.12),
        yaxis=dict(tickprefix="$", tickformat=",.0f"),
    )

    div_table = dash_table.DataTable(
        data=div_df.to_dict("records"),
        columns=[{"name": c, "id": c} for c in div_df.columns],
        sort_action="native",
        style_header={
            "backgroundColor": "#16213e", "color": "#e0e0e0",
            "fontWeight": "bold", "fontSize": "0.8rem",
            "borderBottom": "2px solid #4caf50",
        },
        style_cell={
            "backgroundColor": "#1a1a2e", "color": "#e0e0e0",
            "fontSize": "0.8rem", "padding": "6px 12px",
            "border": "1px solid #2a2a4a",
        },
        style_data_conditional=[
            {"if": {"filter_query": "{Forward Yield %} >= 5", "column_id": "Forward Yield %"},
             "color": "#00e676", "fontWeight": "bold"},
            {"if": {"filter_query": "{Buyback Yield %} > 0", "column_id": "Buyback Yield %"},
             "color": "#00e676"},
            {"if": {"filter_query": "{Buyback Yield %} < 0", "column_id": "Buyback Yield %"},
             "color": "#ff6b6b"},
            {"if": {"filter_query": "{Total SH Yield %} >= 5", "column_id": "Total SH Yield %"},
             "color": "#00e676", "fontWeight": "bold"},
        ],
    )

    div_impact = dbc.Card(
        dbc.CardBody([
            html.H6("Total Shareholder Yield", className="text-light mb-3"),
            dbc.Row([
                dbc.Col([
                    html.P("Wtd Div Yield", className="text-muted mb-0",
                           style={"fontSize": "0.7rem", "textTransform": "uppercase"}),
                    html.H4(f"{port_avg_yield:.2f}%", className="text-success mb-0"),
                ], md=2),
                dbc.Col([
                    html.P("Wtd Buyback Yield", className="text-muted mb-0",
                           style={"fontSize": "0.7rem", "textTransform": "uppercase"}),
                    html.H4(f"{port_bb_yield:+.2f}%",
                             className=f"{'text-success' if port_bb_yield >= 0 else 'text-danger'} mb-0"),
                ], md=2),
                dbc.Col([
                    html.P("Total SH Yield", className="text-muted mb-0",
                           style={"fontSize": "0.7rem", "textTransform": "uppercase"}),
                    html.H4(f"{port_total_sh_yield:.2f}%", className="text-warning mb-0"),
                ], md=2),
                dbc.Col([
                    html.P("Est. Annual Income", className="text-muted mb-0",
                           style={"fontSize": "0.7rem", "textTransform": "uppercase"}),
                    html.H4(f"${total_income:,.0f}", className="text-info mb-0"),
                ], md=2),
                dbc.Col([
                    html.P("Price-Only Return (ann.)", className="text-muted mb-0",
                           style={"fontSize": "0.7rem", "textTransform": "uppercase"}),
                    html.H4(f"{price_ann:.2%}", className="mb-0"),
                ], md=2),
                dbc.Col([
                    html.P("Total Return est. (ann. + TSY)", className="text-muted mb-0",
                           style={"fontSize": "0.7rem", "textTransform": "uppercase"}),
                    html.H4(f"{total_ret_with_div:.2%}", className="text-warning mb-0"),
                ], md=2),
            ]),
        ]),
        style={"backgroundColor": "#1a1a2e", "border": "1px solid #4caf50"},
        className="mb-3 mt-2",
    )

    div_section = html.Div([
        html.H5("Total Shareholder Yield — Dividends + Buybacks", className="text-light mt-4 mb-2"),
        div_impact,
        div_table,
        dbc.Row([
            dbc.Col(dcc.Graph(figure=reinvest_fig, config={"displayModeBar": False}), md=6),
            dbc.Col(dcc.Graph(figure=proj_fig, config={"displayModeBar": False}), md=6),
        ], className="mt-3"),
    ])

    # ── Trade log ────────────────────────────────────────────
    trade_section = html.Div()
    log_path = DATA / "trade_log.csv"
    if log_path.exists():
        tlog = pd.read_csv(log_path)
        trade_table = dash_table.DataTable(
            data=tlog.to_dict("records"),
            columns=[{"name": c, "id": c} for c in tlog.columns],
            sort_action="native",
            style_header={
                "backgroundColor": "#16213e", "color": "#e0e0e0",
                "fontWeight": "bold", "fontSize": "0.78rem",
                "borderBottom": "2px solid #00bcd4",
            },
            style_cell={
                "backgroundColor": "#1a1a2e", "color": "#e0e0e0",
                "fontSize": "0.78rem", "padding": "5px 10px",
                "border": "1px solid #2a2a4a",
            },
            page_size=10,
        )
        trade_section = html.Div([
            html.H5("Trade Log", className="text-light mt-4 mb-2"),
            trade_table,
        ])

    # ━━ Assemble layout ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
    return html.Div([
        kpis,

        # Performance + drawdown
        dbc.Row([
            dbc.Col(dcc.Graph(figure=perf_fig, config={"displayModeBar": False}), md=12),
        ], className="mb-2"),
        dbc.Row([
            dbc.Col(dcc.Graph(figure=dd_fig, config={"displayModeBar": False}), md=12),
        ], className="mb-3"),

        # Exposure pies
        dbc.Row([
            dbc.Col(dcc.Graph(figure=ctry_fig), md=6),
            dbc.Col(dcc.Graph(figure=sec_fig), md=6),
        ], className="mb-3"),

        # Positions table
        html.H5("Holdings", className="text-light mb-2"),
        pos_table,

        # Individual stock chart
        dbc.Row(dbc.Col(
            dcc.Graph(figure=stock_fig, config={"displayModeBar": False}),
        ), className="mt-4 mb-3"),

        # Two-column: risk metrics | CAPM
        dbc.Row([
            dbc.Col([
                html.H5("Risk Metrics", className="text-light mb-2"),
                risk_table,
            ], md=5),
            dbc.Col(
                dcc.Graph(figure=capm_fig), md=7,
            ),
        ], className="mb-3"),

        # Correlation heatmap
        dbc.Row(dbc.Col(
            dcc.Graph(figure=corr_fig),
        ), className="mb-3"),

        # Fundamentals
        fund_section,

        # Dividends
        div_section,

        # Trade log
        trade_section,

    ]), f"Last refreshed: {last_date}"


# ── Run ───────────────────────────────────────────────────────────
if __name__ == "__main__":
    port = int(os.environ.get("PORT", 8050))
    app.run(debug=False, host="0.0.0.0", port=port)
