"""
FINN3021 — Interactive Portfolio Dashboard
==========================================
Run:  python dashboard/app.py
Open:  http://127.0.0.1:8050

Reads holdings from data/outputs/portfolio_snapshot.csv (generated by
02_portfolio_dashboard.ipynb).  Pulls live prices via yfinance on each
page load.  Re-run the notebook → refresh the browser to pick up changes.
"""

import os
import pathlib
import threading
import time
import traceback
from datetime import date

import dash
import dash_bootstrap_components as dbc
import numpy as np
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
import plotly.io as pio
import yfinance as yf

# ── Global Plotly font ────────────────────────────────────────────
_FONT_FAMILY = "Aptos, Calibri, 'Segoe UI', Helvetica, Arial, sans-serif"
pio.templates["plotly_white"].layout.font = dict(family=_FONT_FAMILY)
from dash import Input, Output, callback, dash_table, dcc, html
from scipy import stats as sp_stats
import statsmodels.api as sm

# ── Paths ─────────────────────────────────────────────────────────
ROOT = pathlib.Path(__file__).resolve().parent.parent
DATA = ROOT / "data" / "outputs"

# ── Constants (must match the notebook) ───────────────────────────
INCEPTION = date(2026, 3, 9)
BENCHMARK = "ACWX"
RISK_FREE_ANNUAL = 0.043
NOTIONAL = 1_000_000
HORIZON_YRS = 10

COUNTRY_NAMES = {
    "JP": "Japan", "ZA": "South Africa", "IN": "India",
    "GB": "United Kingdom", "QA": "Qatar", "US": "United States",
    "BR": "Brazil", "TW": "Taiwan", "ID": "Indonesia",
    "MX": "Mexico", "IT": "Italy", "CH": "Switzerland",
    "DE": "Germany", "TH": "Thailand", "SA": "Saudi Arabia",
    "FR": "France",
}

# Chart export config — hover to see mode bar, camera icon downloads
# transparent PNG at 3× resolution (great for reports)
CHART_CONFIG = {
    "displayModeBar": "hover",
    "toImageButtonOptions": {
        "format": "png",
        "scale": 3,
    },
    "modeBarButtonsToRemove": ["select2d", "lasso2d", "autoScale2d"],
}

# ── Ticker aliases (corporate actions since inception) ────────────
# The snapshot CSV records the symbol a holding was BOUGHT under. When a company
# is renamed or absorbed, that symbol stops resolving and yfinance returns a
# silent all-NaN column rather than an error.
#
# ODPV3.SA (Odontoprev) → SAUD3.SA (Bradsaúde S.A.). Verified 20 Aug 2026: the
# snapshot/SAUD3 price ratio is 1.0055 at inception AND at the 20 Apr snapshot
# date — constant, so there is no share-exchange ratio to apply (that would show
# as a clean multiple). The residual 0.55% is dividend re-adjustment in the
# back-history. Share count therefore carries over 1:1, untouched.
#
# Prices are downloaded under the live symbol and renamed back to the portfolio's
# symbol, so shares, cost basis and every downstream join keep working unchanged.
TICKER_ALIASES = {
    "ODPV3.SA": "SAUD3.SA",
}


# ── yfinance .info memo ───────────────────────────────────────────
# The fundamentals table and the dividends table each loop over all 21 holdings
# calling yf.Ticker(t).info — the identical network round-trip, twice per
# rebuild, plus a slow 404 retry for any delisted symbol. One shared cache halves
# the cold build and makes background refreshes cheap. Company-level info (market
# cap, currency, payout ratio) changes far too slowly to justify re-fetching it
# within a single hour.
_INFO_TTL = int(os.environ.get("DASHBOARD_INFO_TTL", 3600))
_info_cache: dict = {}
_info_lock = threading.Lock()


def _ticker_info(tk: str) -> dict:
    """yf.Ticker(tk).info, memoised with a TTL. Never raises.

    Resolves TICKER_ALIASES first. The price path already downloads under the
    live symbol (see pull_live_prices); doing the same here keeps the two in
    step. Without this, a renamed holding 404s on every .info call and every
    field sourced from it — market cap, volume, payout ratio, buyback yield —
    comes back empty, which is how Odontoprev went blank across the
    fundamentals and dividends tables while its price series kept working.

    Cached under the live symbol so aliased and direct lookups share one entry.
    """
    live = TICKER_ALIASES.get(tk, tk)
    now = time.time()
    with _info_lock:
        hit = _info_cache.get(live)
        if hit and (now - hit[0]) < _INFO_TTL:
            return hit[1]
    try:
        info = yf.Ticker(live).info or {}
    except Exception:
        info = {}
    with _info_lock:
        _info_cache[live] = (now, info)
    return info


# ── Load data from notebook CSVs ─────────────────────────────────

def load_snapshot():
    """Read the latest portfolio_snapshot.csv."""
    return pd.read_csv(DATA / "portfolio_snapshot.csv")


def load_fundamentals():
    """Load screen-level fundamentals for holdings."""
    screen = pd.read_csv(DATA / "portfolio_screen_final20.csv")
    snap = load_snapshot()
    # Build name→ticker map from snapshot (only names present in screen CSV)
    name_map = {
        "AUTOTRADER GROUP PLC":          "AUTO.L",
        "KAKAKU.COM INC":                "2371.T",
        "CLICKS GROUP LTD":              "CLS.JO",
        "ITC LTD":                       "ITC.NS",
        "ODONTOPREV SA":                 "ODPV3.SA",
        "NEXT PLC":                      "NXT.L",
        "CROMPTON GREAVES CONSUMER":     "CROMPTON.NS",
        "RECRUIT HOLDINGS CO LTD":       "6098.T",
        "HANJAYA MANDALA SAMPOERNA":     "HMSP.JK",
        "KIMBERLY-CLARK DE MEXICO SA":   "KIMBERA.MX",
        "MR PRICE GROUP LTD":            "MRP.JO",
        "MARUWA CO LTD":                 "5344.T",
        "DORMAKABA HOLDINGS AG":         "DOKA.SW",
        "BUMRUNGRAD HOSPITAL PCL":       "BH.BK",
    }
    screen["ticker"] = screen["company_name"].map(name_map)
    matched = screen[screen["ticker"].isin(snap["ticker"])].copy()
    cols = [c for c in ["ticker", "rk", "piotroski", "roic_5y_avg",
                        "fcf_ev_5y_avg", "div_yield", "pe_ratio",
                        "net_debt_ebitda", "altman_z", "composite",
                        "fcf_growth_5y", "driver"] if c in matched.columns]
    return matched[cols].set_index("ticker")


def pull_live_prices(tickers, end_date=None):
    """Pull adjusted close prices from yfinance since inception.

    Returns (prices, dead) where `dead` lists tickers yfinance returned nothing
    for. Yahoo silently hands back an all-NaN column for a delisted or dropped
    symbol rather than raising, so a caller that does not check ends up with a
    column of NaN masquerading as data — which is how one dead ticker used to
    wipe out the whole correlation matrix.
    """
    start = (pd.Timestamp(INCEPTION) - pd.Timedelta(days=5)).strftime("%Y-%m-%d")
    kw = dict(start=start, auto_adjust=True, progress=False)
    if end_date:
        kw["end"] = (pd.Timestamp(end_date) + pd.Timedelta(days=1)).strftime("%Y-%m-%d")
    # Download under the current live symbol, then rename back to the symbol the
    # portfolio holds, so callers never have to know a rename happened.
    fetch = [TICKER_ALIASES.get(t, t) for t in tickers]
    back = {TICKER_ALIASES.get(t, t): t for t in tickers}
    raw = yf.download(fetch, **kw)
    if isinstance(raw.columns, pd.MultiIndex):
        prices = raw["Close"].copy()
    else:
        prices = raw[["Close"]].copy()
        prices.columns = fetch
    prices = prices.rename(columns=back)
    # A symbol yfinance drops entirely is absent from the frame, not just NaN.
    prices = prices.reindex(columns=list(tickers))
    prices = prices.ffill()
    prices = prices[prices.index >= pd.Timestamp(INCEPTION)]
    dead = [t for t in prices.columns if prices[t].isna().all()]
    return prices, dead


def compute_all(end_date=None):
    """Compute every metric from live prices + snapshot CSVs."""
    snap = load_snapshot()
    eq_tickers = snap["ticker"].tolist()
    all_tickers = eq_tickers + [BENCHMARK]
    prices, dead = pull_live_prices(all_tickers, end_date=end_date)

    # A holding Yahoo no longer covers (Odontoprev/ODPV3.SA, delisted from their
    # feed) must not silently vanish: dropping it understates portfolio value and
    # every weight derived from it. Carry it at the last price the snapshot
    # recorded, and flag it so the UI can say so rather than implying it is live.
    stale = [t for t in dead if t in eq_tickers]
    if stale:
        last_known = snap.set_index("ticker")["current_px"]
        for t in stale:
            px = last_known.get(t)
            if pd.notna(px):
                prices[t] = float(px)
    # The benchmark going dark is not recoverable — every relative metric needs it.
    if BENCHMARK in dead:
        raise RuntimeError(f"benchmark {BENCHMARK} returned no price data")

    # Shares & cost from snapshot
    positions = snap.copy()

    shares = positions.set_index("ticker")["shares"]

    # Daily values — 100% equity
    eq_values = prices[eq_tickers].multiply(shares, axis=1)
    port_value = eq_values.sum(axis=1)

    port_return = port_value / port_value.iloc[0] - 1
    bench_return = prices[BENCHMARK] / prices[BENCHMARK].iloc[0] - 1

    # Daily returns
    port_daily = port_value.pct_change().dropna()
    bench_daily = prices[BENCHMARK].pct_change().dropna()
    aligned = pd.DataFrame({"port": port_daily, "bench": bench_daily}).dropna()

    # Per-stock returns
    stock_ret = prices[eq_tickers] / prices[eq_tickers].iloc[0] - 1

    # Latest P&L
    latest = prices[eq_tickers].iloc[-1]
    pos_pnl = positions.copy()
    pos_pnl["current_px"] = pos_pnl["ticker"].map(latest)
    pos_pnl["current_value"] = pos_pnl["shares"] * pos_pnl["current_px"]
    pos_pnl["pnl"] = pos_pnl["current_value"] - pos_pnl["cost_basis"]
    pos_pnl["return_pct"] = pos_pnl["pnl"] / pos_pnl["cost_basis"] * 100
    pos_pnl["weight_now"] = pos_pnl["current_value"] / port_value.iloc[-1] * 100
    pos_pnl["country_name"] = pos_pnl["country"].map(COUNTRY_NAMES)

    # Risk metrics
    ann = 252
    rf_d = (1 + RISK_FREE_ANNUAL) ** (1 / 252) - 1
    p_ann_ret = (1 + aligned["port"].mean()) ** ann - 1
    b_ann_ret = (1 + aligned["bench"].mean()) ** ann - 1
    p_ann_vol = aligned["port"].std() * np.sqrt(ann)
    b_ann_vol = aligned["bench"].std() * np.sqrt(ann)
    excess = aligned["port"] - rf_d
    active = aligned["port"] - aligned["bench"]
    sharpe = excess.mean() / aligned["port"].std() * np.sqrt(ann) if aligned["port"].std() > 0 else 0
    te = active.std() * np.sqrt(ann)
    ir = active.mean() / active.std() * np.sqrt(ann) if active.std() > 0 else 0
    cov_m = np.cov(aligned["port"], aligned["bench"])
    beta = cov_m[0, 1] / cov_m[1, 1] if cov_m[1, 1] > 0 else 0
    jensens_alpha = p_ann_ret - (RISK_FREE_ANNUAL + beta * (b_ann_ret - RISK_FREE_ANNUAL))
    treynor = (p_ann_ret - RISK_FREE_ANNUAL) / beta if beta != 0 else 0
    reg = sp_stats.linregress(aligned["bench"], aligned["port"])
    alpha_ann = reg.intercept * ann
    r2 = reg.rvalue ** 2
    dd_port = (port_value - port_value.cummax()) / port_value.cummax()
    dd_bench = (prices[BENCHMARK] - prices[BENCHMARK].cummax()) / prices[BENCHMARK].cummax()
    down = aligned["port"][aligned["port"] < 0]
    down_vol = down.std() * np.sqrt(ann) if len(down) > 0 else 0
    sortino = (p_ann_ret - RISK_FREE_ANNUAL) / down_vol if down_vol > 0 else 0
    max_dd = abs(dd_port.min())
    calmar = (p_ann_ret - RISK_FREE_ANNUAL) / max_dd if max_dd > 0 else 0
    up_d = aligned[aligned["bench"] > 0]
    dn_d = aligned[aligned["bench"] < 0]
    up_cap = up_d["port"].mean() / up_d["bench"].mean() * 100 if len(up_d) > 0 else 0
    dn_cap = dn_d["port"].mean() / dn_d["bench"].mean() * 100 if len(dn_d) > 0 else 0

    p_daily_std = aligned["port"].std()
    b_daily_std = aligned["bench"].std()

    # ── Active Share ─────────────────────────────────────────
    # AS = 0.5 * Σ|w_port_i - w_bench_i| across all securities.
    # Estimate each holding's benchmark weight via market-cap share of
    # the MSCI ACWI ex-US investable universe (~$32 T free-float mkt cap).
    ACWI_EXUS_MCAP = 32e12  # approximate total free-float market cap (USD)
    # Map currency → rough USD rate (only need order-of-magnitude accuracy)
    _CCY_TO_USD = {
        "JPY": 1/150, "GBp": 1/80, "GBP": 1.27, "ZAc": 1/1800, "ZAR": 1/18,
        "INR": 1/84, "BRL": 1/5.2, "TWD": 1/32, "IDR": 1/16000,
        "MXN": 1/17, "EUR": 1.08, "CHF": 1.10, "THB": 1/36,
        "SAR": 1/3.75, "USD": 1.0,
    }
    port_weights = pos_pnl.set_index("ticker")["weight_now"] / 100
    bench_weights = pd.Series(0.0, index=eq_tickers)
    # market_caps_live.csv is produced by scripts/fetch_market_caps.py and holds
    # mcap_usd for every holding. Reading it replaces 21 sequential
    # yf.Ticker().info round-trips (~8 s of dead time on EVERY cold load) with a
    # single file read. Market caps move far too slowly to be worth 8 s a page —
    # refresh the file by re-running that script. Any ticker missing from the
    # file still falls back to a live lookup, so nothing is lost.
    cached_mcaps = {}
    try:
        _mc = pd.read_csv(DATA / "market_caps_live.csv")
        cached_mcaps = dict(zip(_mc["ticker"], _mc["mcap_usd"]))
    except Exception:
        pass
    for tk in eq_tickers:
        mc_usd = cached_mcaps.get(tk)
        if mc_usd is None or pd.isna(mc_usd):
            try:
                info = _ticker_info(tk)
                mc = info.get("marketCap", 0) or 0
                fx = _CCY_TO_USD.get(info.get("currency", "USD"), 1.0)
                mc_usd = mc * fx
            except Exception:
                mc_usd = 0.0
        bench_weights[tk] = float(mc_usd or 0.0) / ACWI_EXUS_MCAP
    bench_weights = bench_weights.clip(upper=0.05)
    overlap = port_weights.reindex(eq_tickers).fillna(0)
    diff = (overlap - bench_weights).abs().sum()
    bench_only_weight = max(1 - bench_weights.sum(), 0)
    active_share = 0.5 * (diff + bench_only_weight)
    active_share = min(active_share, 1.0)

    # Benchmark equivalents
    b_excess = aligned["bench"] - rf_d
    b_sharpe = b_excess.mean() / aligned["bench"].std() * np.sqrt(ann) if aligned["bench"].std() > 0 else 0
    b_down = aligned["bench"][aligned["bench"] < 0]
    b_down_vol = b_down.std() * np.sqrt(ann) if len(b_down) > 0 else 0
    b_sortino = (b_ann_ret - RISK_FREE_ANNUAL) / b_down_vol if b_down_vol > 0 else 0
    b_treynor = (b_ann_ret - RISK_FREE_ANNUAL) / 1.0  # benchmark beta = 1
    b_max_dd = abs(dd_bench.min())
    b_calmar = (b_ann_ret - RISK_FREE_ANNUAL) / b_max_dd if b_max_dd > 0 else 0

    risk = {
        "Ann. Return": f"{p_ann_ret:.2%}", "Ann. Vol": f"{p_ann_vol:.2%}",
        "Daily Std Dev": f"{p_daily_std:.4%}",
        "Sharpe": f"{sharpe:.2f}", "Sortino": f"{sortino:.2f}",
        "Treynor": f"{treynor:.4f}", "Calmar": f"{calmar:.2f}",
        "Info Ratio": f"{ir:.2f}", "Tracking Error": f"{te:.2%}",
        "Beta": f"{beta:.3f}", "Alpha (ann)": f"{alpha_ann:.2%}",
        "Jensen's α": f"{jensens_alpha:.2%}",
        "R²": f"{r2:.3f}", "Max DD": f"{dd_port.min():.2%}",
        "Downside Vol": f"{down_vol:.2%}",
        "Up Capture": f"{up_cap:.1f}%", "Down Capture": f"{dn_cap:.1f}%",
        "Active Share": f"{active_share:.1%}",
    }
    bench_risk = {
        "Ann. Return": f"{b_ann_ret:.2%}", "Ann. Vol": f"{b_ann_vol:.2%}",
        "Daily Std Dev": f"{b_daily_std:.4%}",
        "Sharpe": f"{b_sharpe:.2f}", "Sortino": f"{b_sortino:.2f}",
        "Treynor": f"{b_treynor:.4f}", "Calmar": f"{b_calmar:.2f}",
        "Info Ratio": "—", "Tracking Error": "—",
        "Beta": "1.000", "Alpha (ann)": "0.00%",
        "Jensen's α": "0.00%",
        "R²": "1.000", "Max DD": f"{dd_bench.min():.2%}",
        "Downside Vol": f"{b_down_vol:.2%}",
        "Up Capture": "100.0%", "Down Capture": "100.0%",
        "Active Share": "0.0%",
    }
    risk_df = pd.DataFrame({
        "Metric": list(risk.keys()),
        "Portfolio": list(risk.values()),
        "Benchmark": list(bench_risk.values()),
    })

    # ── Correlation ──────────────────────────────────────────
    # `.dropna()` defaults to how="any", so a single all-NaN column (one dead
    # ticker) deleted EVERY row and left an empty frame — corr() then returned
    # all-NaN and the heatmap rendered blank. Three changes:
    #   · drop dead/stale tickers by column, not by row
    #   · drop rows only when the whole row is empty (a holiday in one market
    #     should not discard that day for the other twenty names)
    #   · correlate pairwise with a min_periods floor, so a partial gap costs
    #     one cell instead of the matrix
    corr_tickers = [t for t in eq_tickers if t not in stale]
    eq_dr = prices[corr_tickers].pct_change()
    eq_dr = eq_dr.dropna(axis=1, how="all").dropna(how="all")
    name_map = positions.set_index("ticker")["name"]
    eq_dr.columns = [name_map.get(t, t) for t in eq_dr.columns]
    corr = eq_dr.corr(min_periods=20)

    # ── FX attribution ───────────────────────────────────────
    # Map each country code → yfinance FX ticker (CCY→USD rate)
    _FX_MAP = {
        "GB": "GBPUSD=X", "JP": "JPYUSD=X", "ZA": "ZARUSD=X",
        "IN": "INRUSD=X", "BR": "BRLUSD=X", "TW": "TWDUSD=X",
        "ID": "IDRUSD=X", "MX": "MXNUSD=X", "IT": "EURUSD=X",
        "FR": "EURUSD=X", "DE": "EURUSD=X", "CH": "CHFUSD=X",
        "TH": "THBUSD=X", "SA": "SARUSD=X",
    }
    fx_tickers = list(set(_FX_MAP.values()))
    try:
        fx_prices = yf.download(
            fx_tickers,
            start=(pd.Timestamp(prices.index[0]) - pd.Timedelta(days=5)).strftime("%Y-%m-%d"),
            end=(pd.Timestamp(prices.index[-1]) + pd.Timedelta(days=1)).strftime("%Y-%m-%d"),
            auto_adjust=True, progress=False,
        )
        if isinstance(fx_prices.columns, pd.MultiIndex):
            fx_prices = fx_prices["Close"]
        fx_prices = fx_prices.ffill().reindex(prices.index, method="ffill")
    except Exception:
        fx_prices = pd.DataFrame(index=prices.index)

    fx_attr = []
    for _, row in positions.iterrows():
        tk = row["ticker"]
        ctry = row["country"]
        fx_tk = _FX_MAP.get(ctry)
        local_ret = (prices[tk].iloc[-1] / prices[tk].iloc[0] - 1) * 100
        if fx_tk and fx_tk in fx_prices.columns:
            fx_start = fx_prices[fx_tk].iloc[0]
            fx_end = fx_prices[fx_tk].iloc[-1]
            if pd.notna(fx_start) and pd.notna(fx_end) and fx_start > 0:
                fx_ret = (fx_end / fx_start - 1) * 100
                usd_ret = ((1 + local_ret / 100) * (1 + fx_ret / 100) - 1) * 100
            else:
                fx_ret = 0.0
                usd_ret = local_ret
        else:
            fx_ret = 0.0
            usd_ret = local_ret
        fx_attr.append({
            "name": row["name"], "ticker": tk, "country": ctry,
            "local_ret": round(local_ret, 2),
            "fx_ret": round(fx_ret, 2),
            "usd_ret": round(usd_ret, 2),
        })
    fx_df = pd.DataFrame(fx_attr)

    # ── Fama-French 5-factor decomposition ─────────────────────
    # ETF-proxy factors (Kenneth French data lags; ETFs are real-time)
    _FF_TICKERS = ["ACWX", "SCZ", "EFA", "EFV", "EFG", "IQLT", "EFAV"]
    try:
        ff_raw = yf.download(
            _FF_TICKERS,
            start=(pd.Timestamp(prices.index[0]) - pd.Timedelta(days=5)).strftime("%Y-%m-%d"),
            end=(pd.Timestamp(prices.index[-1]) + pd.Timedelta(days=1)).strftime("%Y-%m-%d"),
            auto_adjust=True, progress=False,
        )
        if isinstance(ff_raw.columns, pd.MultiIndex):
            ff_px = ff_raw["Close"]
        else:
            ff_px = ff_raw
        ff_px = ff_px.ffill().reindex(prices.index, method="ffill")
        ff_ret = ff_px.pct_change().dropna()

        rf_daily = (1 + RISK_FREE_ANNUAL) ** (1 / 252) - 1
        ff_factors = pd.DataFrame({
            "MKT-RF": ff_ret["ACWX"] - rf_daily,
            "SMB":    ff_ret["SCZ"] - ff_ret["EFA"],
            "HML":    ff_ret["EFV"] - ff_ret["EFG"],
            "RMW":    ff_ret["IQLT"] - ff_ret["ACWX"],
            "CMA":    ff_ret["EFAV"] - ff_ret["ACWX"],
        })
        # Align with portfolio excess returns
        y = (port_daily - rf_daily).reindex(ff_factors.index).dropna()
        X = ff_factors.reindex(y.index).dropna()
        y = y.reindex(X.index)
        X_const = sm.add_constant(X)
        ff5_model = sm.OLS(y, X_const).fit()
        ff5_result = {
            "params": ff5_model.params,
            "tvalues": ff5_model.tvalues,
            "pvalues": ff5_model.pvalues,
            "rsquared": ff5_model.rsquared,
            "rsquared_adj": ff5_model.rsquared_adj,
            "alpha_ann": ff5_model.params.get("const", 0) * 252,
            "nobs": int(ff5_model.nobs),
            "factor_sum": X.sum().to_dict(),   # cumulative factor returns over period
            "port_excess_cum": float(y.sum()),  # cumulative portfolio excess return
        }
    except Exception:
        ff5_result = {"error": traceback.format_exc()}

    result = {
        "prices": prices,
        "port_return": port_return,
        "bench_return": bench_return,
        "port_value": port_value,
        "pos_pnl": pos_pnl,
        "stock_ret": stock_ret,
        "dd_port": dd_port,
        "dd_bench": dd_bench,
        "risk_df": risk_df,
        "corr": corr,
        "aligned": aligned,
        "reg": reg,
        "beta": beta,
        "alpha_ann": alpha_ann,
        "r2": r2,
        "sharpe": sharpe,
        "p_ann_ret": p_ann_ret,
        "p_ann_vol": p_ann_vol,
        "max_dd_val": dd_port.min(),
        "ir": ir,
        "name_map": name_map,
        "fx_df": fx_df,
        "ff5": ff5_result,
        "stale_tickers": stale,
    }
    return result
app = dash.Dash(
    __name__,
    external_stylesheets=[dbc.themes.FLATLY],
    title="FINN3021 Portfolio Dashboard",
    suppress_callback_exceptions=True,
)
app.index_string = app.index_string.replace(
    "</head>",
    "<style>* { font-family: Aptos, Calibri, 'Segoe UI', Helvetica, Arial, sans-serif !important; }</style></head>",
)
server = app.server  # expose for gunicorn


def _build_ff5_section(d):
    """Build the Fama-French 5-factor regression section."""
    ff5 = d.get("ff5")
    if ff5 is None or "error" in (ff5 or {}):
        err_msg = (ff5 or {}).get("error", "Unknown error")
        return html.Div([
            html.P("FF5 factor data unavailable for this period.", className="text-muted"),
            html.Pre(err_msg, style={"fontSize": "0.7rem", "color": "#dc3545",
                                     "whiteSpace": "pre-wrap", "maxHeight": "200px",
                                     "overflow": "auto"}),
        ])

    factors = ["const", "MKT-RF", "SMB", "HML", "RMW", "CMA"]
    nice = {"const": "Alpha (daily)", "MKT-RF": "Market", "SMB": "Size (Small-Big)",
            "HML": "Value (High-Low)", "RMW": "Profitability (Robust-Weak)",
            "CMA": "Investment (Cons.-Agg.)"}
    rows = []
    for f in factors:
        coeff = ff5["params"].get(f, 0)
        t = ff5["tvalues"].get(f, 0)
        p = ff5["pvalues"].get(f, 1)
        sig = "***" if p < 0.01 else "**" if p < 0.05 else "*" if p < 0.10 else ""
        rows.append({
            "Factor": nice.get(f, f),
            "Coefficient": round(coeff, 6) if f == "const" else round(coeff, 4),
            "t-stat": round(t, 2),
            "p-value": round(p, 4),
            "Sig.": sig,
        })
    ff_df = pd.DataFrame(rows)

    ff_table = dash_table.DataTable(
        data=ff_df.to_dict("records"),
        columns=[{"name": c, "id": c} for c in ff_df.columns],
        style_header={
            "backgroundColor": "#f0f0f0", "color": "#212529",
            "fontWeight": "bold", "fontSize": "0.82rem",
            "borderBottom": "2px solid #495057",
        },
        style_cell={
            "backgroundColor": "white", "color": "#212529",
            "fontSize": "0.82rem", "padding": "6px 14px",
            "border": "1px solid #dee2e6",
        },
        style_data_conditional=[
            {"if": {"filter_query": '{Sig.} contains "**"'},
             "fontWeight": "bold", "color": "#198754"},
            {"if": {"filter_query": '{Coefficient} < 0', "column_id": "Coefficient"},
             "color": "#dc3545"},
        ],
    )

    # Bar chart of factor loadings (exclude alpha)
    load_factors = [f for f in factors if f != "const"]
    coeffs = [ff5["params"].get(f, 0) for f in load_factors]
    colours = ["#198754" if c >= 0 else "#dc3545" for c in coeffs]
    bar_fig = go.Figure(go.Bar(
        x=[nice.get(f, f) for f in load_factors],
        y=coeffs,
        marker_color=colours,
        text=[f"{c:.3f}" for c in coeffs],
        textposition="outside",
        textfont=dict(size=12),
    ))
    y_max = max(abs(c) for c in coeffs) * 1.4
    bar_fig.update_layout(
        title=f"FF5 Factor Loadings  ·  R² = {ff5['rsquared']:.3f}  ·  "
              f"α (ann.) = {ff5['alpha_ann']:.2%}  ·  n = {ff5['nobs']}",
        template="plotly_white", paper_bgcolor="white",
        plot_bgcolor="#f8f9fa", yaxis_title="Loading (β)",
        height=560, margin=dict(l=50, r=20, t=80, b=140),
        xaxis=dict(tickangle=-30, tickfont=dict(size=10)),
        yaxis=dict(range=[-y_max, y_max]),
    )

    proxy_note = html.P(
        "Factor proxies: MKT-RF = ACWX − Rf · SMB = SCZ − EFA · "
        "HML = EFV − EFG · RMW = IQLT − ACWX · CMA = EFAV − ACWX. "
        f"Significance: *** p<0.01, ** p<0.05, * p<0.10. "
        f"Adj. R² = {ff5['rsquared_adj']:.3f}.",
        className="text-muted mt-2", style={"fontSize": "0.72rem"},
    )

    # ── Return attribution breakdown ──────────────────────────
    load_factor_names = ["MKT-RF", "SMB", "HML", "RMW", "CMA"]
    factor_sum = ff5.get("factor_sum", {})
    alpha_contrib = ff5["params"].get("const", 0) * ff5["nobs"]
    factor_contribs = {
        f: ff5["params"].get(f, 0) * factor_sum.get(f, 0)
        for f in load_factor_names
    }
    total_explained = alpha_contrib + sum(factor_contribs.values())
    port_excess = ff5.get("port_excess_cum", total_explained)
    residual = port_excess - total_explained

    def _sign(v): return f"+{v:.2%}" if v >= 0 else f"{v:.2%}"

    breakdown_rows = [
        f"| {'Source':<36} | {'Contribution':>12} |",
        f"| {'-'*36} | {'-'*12} |",
        f"| {'Alpha (manager skill)':<36} | {_sign(alpha_contrib):>12} |",
    ]
    for f in load_factor_names:
        label = nice.get(f, f)
        b = ff5["params"].get(f, 0)
        contrib = factor_contribs[f]
        breakdown_rows.append(
            f"| {label + f' (β={b:+.3f})':<36} | {_sign(contrib):>12} |"
        )
    breakdown_rows += [
        f"| {'Residual (ε)':<36} | {_sign(residual):>12} |",
        f"| {'**Total portfolio excess return**':<36} | **{_sign(port_excess):>10}** |",
    ]
    breakdown_md = dcc.Markdown(
        "**Return Attribution — FF5 Decomposition**  \n"
        "*Contribution = factor loading × cumulative factor return over evaluation period*\n\n"
        + "\n".join(breakdown_rows),
        style={"fontSize": "0.82rem", "marginTop": "12px"},
    )

    return html.Div([
        html.H5("Fama-French 5-Factor Decomposition",
                 className="text-dark mt-4 mb-2"),
        dcc.Graph(figure=bar_fig, config=CHART_CONFIG),
        dbc.Accordion([
            dbc.AccordionItem(
                html.Div([ff_table, breakdown_md, proxy_note]),
                title="Regression Coefficients & Return Attribution",
            ),
        ], start_collapsed=True, className="mb-2"),
    ])


def _build_fx_section(d):
    """Build the FX / local return attribution table and chart."""
    fx = d["fx_df"].copy()
    fx = fx.sort_values("usd_ret", ascending=False)

    # Grouped bar chart
    fx_fig = go.Figure()
    fx_fig.add_trace(go.Bar(
        x=fx["name"], y=fx["local_ret"], name="Local Return %",
        marker_color="#0d6efd", opacity=0.85,
    ))
    fx_fig.add_trace(go.Bar(
        x=fx["name"], y=fx["fx_ret"], name="FX Effect %",
        marker_color="#fd7e14", opacity=0.85,
    ))
    fx_fig.add_trace(go.Scatter(
        x=fx["name"], y=fx["usd_ret"], name="USD Return %",
        mode="markers+lines", line=dict(color="#198754", width=2),
        marker=dict(size=7, color="#198754"),
    ))
    fx_fig.update_layout(
        title="Return Decomposition — Local Currency vs FX Effect",
        template="plotly_white", paper_bgcolor="white",
        plot_bgcolor="#f8f9fa", barmode="relative",
        yaxis_title="Return (%)", height=400,
        margin=dict(l=50, r=20, t=60, b=80),
        legend=dict(orientation="h", y=1.12),
        xaxis=dict(tickangle=-45, tickfont=dict(size=9)),
    )

    fx_table = dash_table.DataTable(
        data=fx.to_dict("records"),
        columns=[
            {"name": "Name", "id": "name"},
            {"name": "Ticker", "id": "ticker"},
            {"name": "Country", "id": "country"},
            {"name": "Local Ret %", "id": "local_ret"},
            {"name": "FX Effect %", "id": "fx_ret"},
            {"name": "USD Ret %", "id": "usd_ret"},
        ],
        sort_action="native",
        style_header={
            "backgroundColor": "#f0f0f0", "color": "#212529",
            "fontWeight": "bold", "fontSize": "0.8rem",
            "borderBottom": "2px solid #495057",
        },
        style_cell={
            "backgroundColor": "white", "color": "#212529",
            "fontSize": "0.8rem", "padding": "6px 12px",
            "border": "1px solid #dee2e6",
        },
        style_data_conditional=[
            {"if": {"filter_query": "{fx_ret} > 0", "column_id": "fx_ret"},
             "color": "#198754"},
            {"if": {"filter_query": "{fx_ret} < 0", "column_id": "fx_ret"},
             "color": "#dc3545"},
            {"if": {"filter_query": "{usd_ret} > 0", "column_id": "usd_ret"},
             "color": "#198754", "fontWeight": "bold"},
            {"if": {"filter_query": "{usd_ret} < 0", "column_id": "usd_ret"},
             "color": "#dc3545", "fontWeight": "bold"},
        ],
    )

    return html.Div([
        dbc.Row(dbc.Col(
            dcc.Graph(figure=fx_fig, config=CHART_CONFIG),
        ), className="mb-3"),
        dbc.Accordion([
            dbc.AccordionItem(fx_table, title="FX Attribution Detail"),
        ], start_collapsed=True, className="mb-2"),
    ])


def kpi_card(title, value, sub=None, color="primary"):
    """Small KPI card component."""
    body = [html.H4(value, className="card-title mb-0",
                     style={"fontWeight": "700", "fontSize": "1.6rem"})]
    if sub:
        body.append(html.P(sub, className="card-text text-muted mb-0",
                           style={"fontSize": "0.75rem"}))
    return dbc.Card(
        dbc.CardBody([
            html.P(title, className="text-muted mb-1",
                   style={"fontSize": "0.75rem", "textTransform": "uppercase",
                           "letterSpacing": "1px"}),
            *body,
        ]),
        className=f"border-{color}",
        style={"borderLeft": "4px solid", "backgroundColor": "white"},
    )


def build_layout():
    return dbc.Container([
        # ── Header ───────────────────────────────────────────────
        dbc.Row(dbc.Col(html.Div([
            html.H2("FINN3021 — Portfolio Dashboard",
                     className="mb-0", style={"fontWeight": "800"}),
            html.P(
                f"Inception {INCEPTION}  ·  100% equity (conviction-weighted)  ·  "
                f"Benchmark: {BENCHMARK}  ·  Live prices via yfinance",
                className="text-muted mb-0", style={"fontSize": "0.85rem"}),
        ]), width=12), className="my-3"),

        # Refresh button + last-update
        dbc.Row([
            dbc.Col(dbc.Button("↻  Refresh data", id="refresh-btn",
                               color="info", size="sm", className="me-2"),
                    width="auto"),
            dbc.Col(html.Span(id="last-update", className="text-muted",
                              style={"fontSize": "0.8rem"}), width="auto"),
        ], className="mb-3", align="center"),

        # Placeholder for dynamic content
        html.Div(id="dashboard-content"),

        # ── Footer ───────────────────────────────────────────────
        html.Hr(),
        html.P("Data: yfinance · Screen: WRDS Compustat Global · Not investment advice",
               className="text-muted text-center", style={"fontSize": "0.7rem"}),
    ], fluid=True, style={"backgroundColor": "white", "minHeight": "100vh",
                           "padding": "20px 30px",
                           "fontFamily": "Aptos, Calibri, 'Segoe UI', Helvetica, Arial, sans-serif"})


app.layout = build_layout


_CACHE_TTL = int(os.environ.get("DASHBOARD_CACHE_TTL", 900))  # seconds (15 min)
_cache: dict = {"content": None, "last_date": None, "ts": 0.0}
_cache_lock = threading.Lock()
_refreshing = threading.Event()


def _rebuild_into_cache():
    """Recompute and swap into the cache. Safe to call from a worker thread."""
    d = compute_all()
    content, last_date = build_dashboard_content(d)
    with _cache_lock:
        _cache["content"], _cache["last_date"] = content, last_date
        _cache["ts"] = time.time()


def _refresh_async():
    """Refresh in the background, at most one at a time."""
    if _refreshing.is_set():
        return
    _refreshing.set()

    def _work():
        try:
            _rebuild_into_cache()
        except Exception:
            traceback.print_exc()
        finally:
            _refreshing.clear()

    threading.Thread(target=_work, daemon=True).start()


def _build_cached(force=False):
    """Serve the cached page immediately; refresh behind it.

    The old version rebuilt inline whenever the cache was cold or stale, so the
    unlucky visitor who arrived first — or first after the TTL expired — paid the
    full yfinance round-trip before seeing anything. Now a warm cache is always
    returned straight away and any refresh happens on a worker thread
    (stale-while-revalidate). Only a genuinely empty cache blocks, and the
    startup warm-up below means that is normally over before anyone visits.
    """
    with _cache_lock:
        content, last_date, ts = _cache["content"], _cache["last_date"], _cache["ts"]
    now = time.time()

    if content is None:
        _rebuild_into_cache()                 # nothing to show — must block once
        with _cache_lock:
            content, last_date, ts = _cache["content"], _cache["last_date"], _cache["ts"]
    elif force:
        _rebuild_into_cache()                 # user asked explicitly — make them wait
        with _cache_lock:
            content, last_date, ts = _cache["content"], _cache["last_date"], _cache["ts"]
        now = time.time()
    elif (now - ts) > _CACHE_TTL:
        _refresh_async()                      # hand back stale, update behind it

    return content, last_date, int(now - ts)


def _warm_cache_on_start():
    """Build the page once at boot so the first visitor never waits."""
    def _work():
        try:
            _rebuild_into_cache()
            print("[dashboard] cache warm — visuals will load instantly")
        except Exception:
            traceback.print_exc()
    threading.Thread(target=_work, daemon=True).start()


@callback(
    Output("dashboard-content", "children"),
    Output("last-update", "children"),
    Input("refresh-btn", "n_clicks"),
)
def refresh_dashboard(n_clicks):
    """Rebuild the dashboard. Refresh-button click bypasses the cache."""
    content, last_date, age = _build_cached(force=bool(n_clicks))
    return content, f"Last refreshed: {last_date}  ·  cached {age}s ago"


def build_dashboard_content(d):
    """Build all dashboard visuals from a compute_all() result dict."""
    pos = d["pos_pnl"]
    last_date = d["prices"].index[-1].strftime("%d %b %Y %H:%M")
    total_ret = d["port_return"].iloc[-1]
    bench_ret = d["bench_return"].iloc[-1]
    active_ret = total_ret - bench_ret

    # Load fundamentals
    try:
        fundas = load_fundamentals()
    except Exception:
        fundas = pd.DataFrame()

    # ── KPI Cards ────────────────────────────────────────────
    ret_color = "success" if total_ret >= 0 else "danger"
    act_color = "success" if active_ret >= 0 else "danger"
    kpis = dbc.Row([
        dbc.Col(kpi_card("Portfolio Value",
                         f"${d['port_value'].iloc[-1]:,.0f}",
                         f"from $1,000,000", "info"), md=2),
        dbc.Col(kpi_card("Total Return",
                         f"{total_ret:+.2%}", "since inception", ret_color), md=2),
        dbc.Col(kpi_card("Active Return",
                         f"{active_ret:+.2%}", f"vs {BENCHMARK}", act_color), md=2),
        dbc.Col(kpi_card("Ann. Volatility",
                         f"{d['p_ann_vol']:.2%}", "std dev (ann.)", "warning"), md=2),
        dbc.Col(kpi_card("Sharpe Ratio",
                         f"{d['sharpe']:.2f}", "annualised", "warning"), md=2),
        dbc.Col(kpi_card("Max Drawdown",
                         f"{d['max_dd_val']:.2%}", "from peak", "danger"), md=2),
    ], className="mb-4 g-3")

    # ── Performance chart ────────────────────────────────────
    perf_fig = go.Figure()
    perf_fig.add_trace(go.Scatter(
        x=d["port_return"].index, y=d["port_return"] * 100,
        name="Portfolio", line=dict(color="#0d6efd", width=2.5),
    ))
    perf_fig.add_trace(go.Scatter(
        x=d["bench_return"].index, y=d["bench_return"] * 100,
        name=f"Benchmark ({BENCHMARK})",
        line=dict(color="#dc3545", width=2, dash="dash"),
    ))
    perf_fig.add_trace(go.Scatter(
        x=d["port_return"].index,
        y=(d["port_return"] - d["bench_return"]) * 100,
        name="Active return", fill="tozeroy",
        line=dict(color="rgba(40,167,69,0.4)", width=0),
        fillcolor="rgba(40,167,69,0.12)",
    ))
    perf_fig.update_layout(
        title="Cumulative Return — Portfolio vs Benchmark",
        template="plotly_white", paper_bgcolor="white",
        plot_bgcolor="#f8f9fa", yaxis_title="Return (%)",
        legend=dict(orientation="h", y=1.12),
        height=420, margin=dict(l=50, r=20, t=60, b=40),
        hovermode="x unified",
    )

    # ── Drawdown chart ───────────────────────────────────────
    dd_fig = go.Figure()
    dd_fig.add_trace(go.Scatter(
        x=d["dd_port"].index, y=d["dd_port"] * 100,
        name="Portfolio", fill="tozeroy",
        line=dict(color="#dc3545", width=1.5),
        fillcolor="rgba(220,53,69,0.2)",
    ))
    dd_fig.add_trace(go.Scatter(
        x=d["dd_bench"].index, y=d["dd_bench"] * 100,
        name="Benchmark", line=dict(color="#fd7e14", width=1, dash="dot"),
    ))
    dd_fig.update_layout(
        title="Drawdown from Peak",
        template="plotly_white", paper_bgcolor="white",
        plot_bgcolor="#f8f9fa", yaxis_title="Drawdown (%)",
        legend=dict(orientation="h", y=1.12),
        height=300, margin=dict(l=50, r=20, t=60, b=40),
        hovermode="x unified",
    )

    # ── Country & sector pies ────────────────────────────────
    ctry = pos.groupby("country_name")["current_value"].sum().reset_index()
    sec = pos.groupby("sector")["current_value"].sum().reset_index()
    ctry_fig = px.pie(
        ctry, values="current_value", names="country_name",
        hole=0.45, color_discrete_sequence=px.colors.qualitative.Set2,
    )
    ctry_fig.update_layout(
        title="Country Exposure", template="plotly_white",
        paper_bgcolor="white", height=370,
        margin=dict(l=10, r=10, t=50, b=10),
        legend=dict(font=dict(size=10)),
    )
    sec_fig = px.pie(
        sec, values="current_value", names="sector",
        hole=0.45, color_discrete_sequence=px.colors.qualitative.Pastel,
    )
    sec_fig.update_layout(
        title="Sector Exposure", template="plotly_white",
        paper_bgcolor="white", height=370,
        margin=dict(l=10, r=10, t=50, b=10),
        legend=dict(font=dict(size=10)),
    )

    # ── Positions table ──────────────────────────────────────
    tbl = pos[["name", "ticker", "country", "sector",
               "inception_px", "current_px", "pnl", "return_pct",
               "weight_now"]].copy()
    tbl.columns = ["Name", "Ticker", "Country", "Sector",
                   "Entry Px", "Current Px", "P&L ($)", "Return %", "Weight %"]
    for c in ["Entry Px", "Current Px"]:
        tbl[c] = tbl[c].round(2)
    tbl["P&L ($)"] = tbl["P&L ($)"].round(0)
    tbl["Return %"] = tbl["Return %"].round(2)
    tbl["Weight %"] = tbl["Weight %"].round(2)
    tbl = tbl.sort_values("Return %", ascending=False)

    pos_table = dash_table.DataTable(
        data=tbl.to_dict("records"),
        columns=[{"name": c, "id": c} for c in tbl.columns],
        sort_action="native",
        style_table={"overflowX": "auto"},
        style_header={
            "backgroundColor": "#f0f0f0", "color": "#212529",
            "fontWeight": "bold", "fontSize": "0.8rem",
            "borderBottom": "2px solid #0d6efd",
        },
        style_cell={
            "backgroundColor": "white", "color": "#212529",
            "fontSize": "0.8rem", "padding": "8px 12px",
            "border": "1px solid #dee2e6",
        },
        style_data_conditional=[
            {"if": {"filter_query": "{Return %} > 0", "column_id": "Return %"},
             "color": "#198754", "fontWeight": "bold"},
            {"if": {"filter_query": "{Return %} < 0", "column_id": "Return %"},
             "color": "#dc3545", "fontWeight": "bold"},
            {"if": {"filter_query": "{P&L ($)} > 0", "column_id": "P&L ($)"},
             "color": "#198754"},
            {"if": {"filter_query": "{P&L ($)} < 0", "column_id": "P&L ($)"},
             "color": "#dc3545"},
            {"if": {"state": "active"}, "backgroundColor": "#e9ecef",
             "border": "1px solid #0d6efd"},
        ],
        page_size=25,
    )

    # ── Correlation heatmap ──────────────────────────────────
    corr = d["corr"]
    # Guard the title's average: .stack() on an empty or 1x1 frame raises, and a
    # chart that throws takes the whole callback down rather than degrading.
    if len(corr) > 1:
        _off_diag = corr.where(~np.eye(len(corr), dtype=bool)).stack()
        _avg = _off_diag.mean() if len(_off_diag) else float("nan")
        _avg_txt = f"avg = {_avg:.3f}" if pd.notna(_avg) else "avg unavailable"
    else:
        _avg_txt = "insufficient price history"

    corr_fig = go.Figure(data=go.Heatmap(
        z=corr.values, x=corr.columns, y=corr.index,
        colorscale="RdYlGn_r", zmin=-1, zmax=1,
        text=corr.round(2).values,
        texttemplate="%{text:.2f}",
        textfont={"size": 8},
        hovertemplate="%{x} vs %{y}: %{z:.3f}<extra></extra>",
    ))
    corr_fig.update_layout(
        title=f"Pairwise Correlation  ·  {_avg_txt}",
        template="plotly_white", paper_bgcolor="white",
        plot_bgcolor="#f8f9fa", height=550,
        margin=dict(l=120, r=20, t=60, b=120),
        xaxis=dict(tickangle=45, tickfont=dict(size=9)),
        yaxis=dict(tickfont=dict(size=9)),
    )

    # ── CAPM regression ──────────────────────────────────────
    al = d["aligned"]
    capm_fig = go.Figure()
    capm_fig.add_trace(go.Scatter(
        x=al["bench"] * 100, y=al["port"] * 100,
        mode="markers", name="Daily returns",
        marker=dict(color="#0d6efd", size=6, opacity=0.5),
    ))
    x_line = np.linspace(al["bench"].min(), al["bench"].max(), 100)
    y_line = d["reg"].intercept + d["reg"].slope * x_line
    capm_fig.add_trace(go.Scatter(
        x=x_line * 100, y=y_line * 100,
        mode="lines", name=f"α={d['alpha_ann']:.2%} β={d['beta']:.3f} R²={d['r2']:.3f}",
        line=dict(color="#dc3545", width=2),
    ))
    lim = max(abs(al["bench"].min()), abs(al["bench"].max())) * 100
    capm_fig.add_trace(go.Scatter(
        x=[-lim, lim], y=[-lim, lim], mode="lines", name="β=1",
        line=dict(color="grey", width=1, dash="dot"),
    ))
    capm_fig.update_layout(
        title="CAPM Regression — Portfolio vs Benchmark",
        template="plotly_white", paper_bgcolor="white",
        plot_bgcolor="#f8f9fa",
        xaxis_title=f"Benchmark daily return (%) — {BENCHMARK}",
        yaxis_title="Portfolio daily return (%)",
        height=420, margin=dict(l=50, r=20, t=60, b=50),
        legend=dict(orientation="h", y=-0.18, font=dict(size=10)),
    )

    # ── Risk metrics table ───────────────────────────────────
    risk_table = dash_table.DataTable(
        data=d["risk_df"].to_dict("records"),
        columns=[{"name": c, "id": c} for c in d["risk_df"].columns],
        style_header={
            "backgroundColor": "#f0f0f0", "color": "#212529",
            "fontWeight": "bold", "fontSize": "0.82rem",
            "borderBottom": "2px solid #495057",
        },
        style_cell={
            "backgroundColor": "white", "color": "#212529",
            "fontSize": "0.82rem", "padding": "6px 14px",
            "border": "1px solid #dee2e6",
        },
    )

    # ── Fundamentals table ───────────────────────────────────
    fund_section = html.Div()
    if not fundas.empty:
        fd = fundas.reset_index().merge(
            pos[["ticker", "name", "return_pct"]], on="ticker", how="left"
        )
        for c in ["roic_5y_avg", "fcf_ev_5y_avg", "div_yield", "fcf_growth_5y"]:
            if c in fd.columns:
                fd[c] = (fd[c] * 100).round(1)
        for c in ["composite", "net_debt_ebitda", "altman_z"]:
            if c in fd.columns:
                fd[c] = fd[c].round(2)
        if "pe_ratio" in fd.columns:
            fd["pe_ratio"] = fd["pe_ratio"].round(1)
        fd["return_pct"] = fd["return_pct"].round(1)

        # Pull market cap & daily volume from yfinance (convert to USD)
        # Fetch FX rates once for all needed currencies
        fx_cache = {}
        # yfinance reports currency as minor unit (ZAc, GBp) for some exchanges
        # but marketCap is already in the major unit (ZAR, GBP). Map to major.
        _MINOR_TO_MAJOR = {"ZAC": "ZAR", "GBP": "GBP"}  # GBp→GBP, ZAc→ZAR
        def _to_usd(value, ccy):
            if value is None or ccy is None:
                return None
            ccy = ccy.upper()
            if ccy == "USD":
                return value
            # Map minor-unit label to major currency (no division —
            # marketCap is already in the major unit)
            ccy = _MINOR_TO_MAJOR.get(ccy, ccy)
            if ccy not in fx_cache:
                pair = f"{ccy}USD=X"
                try:
                    rate_data = yf.Ticker(pair).history(period="1d")
                    fx_cache[ccy] = rate_data["Close"].iloc[-1] if len(rate_data) else None
                except Exception:
                    fx_cache[ccy] = None
            rate = fx_cache.get(ccy)
            return value * rate if rate else None

        mcaps, vols = [], []
        for t in fd["ticker"]:
            try:
                info = _ticker_info(t)
                mc = info.get("marketCap")
                ccy = info.get("currency", "USD")
                # Convert local-currency market cap to USD
                mc_usd = _to_usd(mc, ccy) if mc else None
                mcaps.append(round(mc_usd / 1e9, 2) if mc_usd else None)
                vl = info.get("averageDailyVolume10Day") or info.get("volume")
                vols.append(int(vl) if vl else None)
            except Exception:
                mcaps.append(None)
                vols.append(None)
        fd["mkt_cap_bn"] = mcaps
        fd["avg_daily_vol"] = vols

        fd = fd.sort_values("composite", ascending=False)
        show_cols = ["name", "return_pct", "composite", "piotroski",
                     "roic_5y_avg", "fcf_ev_5y_avg", "div_yield",
                     "pe_ratio", "net_debt_ebitda", "mkt_cap_bn",
                     "avg_daily_vol"]
        show_cols = [c for c in show_cols if c in fd.columns]
        nice = {"name": "Name", "return_pct": "Ret %", "composite": "Composite",
                "piotroski": "Piotroski", "roic_5y_avg": "ROIC %",
                "fcf_ev_5y_avg": "FCF/EV %", "div_yield": "Div Yield %",
                "pe_ratio": "P/E", "net_debt_ebitda": "ND/EBITDA",
                "mkt_cap_bn": "Mkt Cap ($B)", "avg_daily_vol": "Avg Daily Vol"}

        # Append average row
        avg_row = {"name": "AVERAGE"}
        num_cols = [c for c in show_cols if c != "name"]
        for c in num_cols:
            avg_row[c] = fd[c].mean() if fd[c].notna().any() else None
            if avg_row[c] is not None:
                if c == "avg_daily_vol":
                    avg_row[c] = int(round(avg_row[c]))
                elif c == "piotroski":
                    avg_row[c] = round(avg_row[c], 1)
                else:
                    avg_row[c] = round(avg_row[c], 2) if isinstance(avg_row[c], float) else avg_row[c]
        fd_display = pd.concat([fd[show_cols], pd.DataFrame([avg_row])], ignore_index=True)

        fund_table = dash_table.DataTable(
            data=fd_display.to_dict("records"),
            columns=[{"name": nice.get(c, c), "id": c} for c in show_cols],
            sort_action="native",
            style_header={
                "backgroundColor": "#f0f0f0", "color": "#212529",
                "fontWeight": "bold", "fontSize": "0.8rem",
                "borderBottom": "2px solid #6c757d",
            },
            style_cell={
                "backgroundColor": "white", "color": "#212529",
                "fontSize": "0.8rem", "padding": "6px 12px",
                "border": "1px solid #dee2e6",
            },
            style_data_conditional=[
                {"if": {"filter_query": '{name} = "AVERAGE"'},
                 "backgroundColor": "#f0f0f0", "fontWeight": "bold",
                 "borderTop": "2px solid #6c757d"},
            ],
        )
        fund_section = html.Div([
            dbc.Accordion([
                dbc.AccordionItem(fund_table, title="Screen Fundamentals"),
            ], start_collapsed=True, className="mt-4 mb-2"),
        ])

    # ── Per-stock sparklines ─────────────────────────────────
    stock_fig = go.Figure()
    names = d["name_map"]
    for t in pos["ticker"]:
        sr = d["stock_ret"][t] * 100
        stock_fig.add_trace(go.Scatter(
            x=sr.index, y=sr,
            name=names.get(t, t),
            mode="lines", line=dict(width=1.5),
            hovertemplate=f"{names.get(t, t)}: " + "%{y:.2f}%<extra></extra>",
        ))
    stock_fig.update_layout(
        title="Individual Stock Returns Since Inception",
        template="plotly_white", paper_bgcolor="white",
        plot_bgcolor="#f8f9fa", yaxis_title="Return (%)",
        height=450, margin=dict(l=50, r=20, t=60, b=40),
        legend=dict(font=dict(size=9)),
        hovermode="x unified",
    )

    # ── Total shareholder yield analysis ─────────────────────
    def _safe_yield(info):
        """Return (trailing, forward) yields as decimals (0.02 = 2%)."""
        raw_fwd = info.get("dividendYield")
        fwd = raw_fwd / 100 if raw_fwd is not None else None
        raw_trail = info.get("trailingAnnualDividendYield")
        if raw_trail is not None and raw_trail > 0:
            ccy = (info.get("currency") or "")
            is_minor = len(ccy) == 3 and ccy[-1].islower()
            trail = raw_trail * 100 if is_minor else raw_trail
        else:
            trail = fwd
        return trail, fwd

    def _buyback_yield(ticker_obj, info):
        """Net buyback yield from most recent annual cash-flow statement."""
        try:
            cf = ticker_obj.cashflow
            mktcap = info.get("marketCap")
            if cf is None or cf.empty or not mktcap or mktcap <= 0:
                return None
            repurchase = 0
            if "Repurchase Of Capital Stock" in cf.index:
                v = cf.loc["Repurchase Of Capital Stock"].dropna()
                if len(v) > 0:
                    repurchase = float(v.iloc[0])
            issuance = 0
            if "Issuance Of Capital Stock" in cf.index:
                v = cf.loc["Issuance Of Capital Stock"].dropna()
                if len(v) > 0:
                    issuance = float(v.iloc[0])
            net_buyback = -(repurchase + issuance)
            return net_buyback / mktcap
        except Exception:
            return None

    def _norm_payout(v):
        if v is None:
            return None
        try:
            v = float(v)
        except (TypeError, ValueError):
            return None
        if np.isnan(v):
            return None
        return v / 100 if v > 1 else v

    div_data = []
    for _, h in pos.iterrows():
        try:
            # Buyback yield reads the cashflow statement off the Ticker object
            # directly, so it needs the alias applied too — _ticker_info only
            # resolves it internally for .info.
            tk = yf.Ticker(TICKER_ALIASES.get(h["ticker"], h["ticker"]))
            info = _ticker_info(h["ticker"])
            trail_y, fwd_y = _safe_yield(info)
            payout  = _norm_payout(info.get("payoutRatio"))
            bb_y    = _buyback_yield(tk, info)
        except Exception:
            trail_y = fwd_y = payout = bb_y = None
        fwd_pct   = round(fwd_y * 100, 2)   if fwd_y   else None
        bb_pct    = round(bb_y * 100, 2)     if bb_y is not None else None
        total_sh  = round((fwd_pct or 0) + (bb_pct or 0), 2)
        div_data.append({
            "Name":            h["name"],
            "Country":         h["country"],
            "Trailing Yield %": round(trail_y * 100, 2) if trail_y else None,
            "Forward Yield %":  fwd_pct,
            "Buyback Yield %":  bb_pct,
            "Total SH Yield %": total_sh,
            "Payout Ratio %":   round(payout * 100, 1)   if payout  else None,
            "Current Value":    round(h["current_value"], 0),
        })
    div_df = pd.DataFrame(div_data)

    # Estimated annual income per holding (dividends only)
    div_df["Est. Ann. Income"] = (
        div_df["Current Value"] * div_df["Forward Yield %"].fillna(div_df["Trailing Yield %"]).fillna(0) / 100
    ).round(0)

    # Portfolio-level summary
    total_eq_value = div_df["Current Value"].sum()
    total_income = div_df["Est. Ann. Income"].sum()
    port_avg_yield = (total_income / total_eq_value * 100) if total_eq_value > 0 else 0
    # Weighted buyback yield
    div_df["_wt"] = div_df["Current Value"] / total_eq_value if total_eq_value > 0 else 0
    port_bb_yield = (div_df["Buyback Yield %"].fillna(0) * div_df["_wt"]).sum()
    port_total_sh_yield = port_avg_yield + port_bb_yield
    div_df.drop(columns=["_wt"], inplace=True)

    price_only_ret = total_ret
    days_held = (d["prices"].index[-1] - d["prices"].index[0]).days
    price_ann = (1 + price_only_ret) ** (365 / max(days_held, 1)) - 1

    div_table = dash_table.DataTable(
        data=div_df.to_dict("records"),
        columns=[{"name": c, "id": c} for c in div_df.columns],
        sort_action="native",
        style_header={
            "backgroundColor": "#f0f0f0", "color": "#212529",
            "fontWeight": "bold", "fontSize": "0.8rem",
            "borderBottom": "2px solid #198754",
        },
        style_cell={
            "backgroundColor": "white", "color": "#212529",
            "fontSize": "0.8rem", "padding": "6px 12px",
            "border": "1px solid #dee2e6",
        },
        style_data_conditional=[
            {"if": {"filter_query": "{Forward Yield %} >= 5", "column_id": "Forward Yield %"},
             "color": "#198754", "fontWeight": "bold"},
            {"if": {"filter_query": "{Buyback Yield %} > 0", "column_id": "Buyback Yield %"},
             "color": "#198754"},
            {"if": {"filter_query": "{Buyback Yield %} < 0", "column_id": "Buyback Yield %"},
             "color": "#ff6b6b"},
            {"if": {"filter_query": "{Total SH Yield %} >= 5", "column_id": "Total SH Yield %"},
             "color": "#198754", "fontWeight": "bold"},
        ],
    )

    div_impact = dbc.Card(
        dbc.CardBody([
            html.H6("Total Shareholder Yield", className="text-dark mb-3"),
            dbc.Row([
                dbc.Col([
                    html.P("Wtd Div Yield", className="text-muted mb-0",
                           style={"fontSize": "0.7rem", "textTransform": "uppercase"}),
                    html.H4(f"{port_avg_yield:.2f}%", className="text-success mb-0"),
                ], md=2),
                dbc.Col([
                    html.P("Wtd Buyback Yield", className="text-muted mb-0",
                           style={"fontSize": "0.7rem", "textTransform": "uppercase"}),
                    html.H4(f"{port_bb_yield:+.2f}%",
                             className=f"{'text-success' if port_bb_yield >= 0 else 'text-danger'} mb-0"),
                ], md=2),
                dbc.Col([
                    html.P("Total SH Yield", className="text-muted mb-0",
                           style={"fontSize": "0.7rem", "textTransform": "uppercase"}),
                    html.H4(f"{port_total_sh_yield:.2f}%", className="text-warning mb-0"),
                ], md=2),
                dbc.Col([
                    html.P("Est. Annual Income", className="text-muted mb-0",
                           style={"fontSize": "0.7rem", "textTransform": "uppercase"}),
                    html.H4(f"${total_income:,.0f}", className="text-info mb-0"),
                ], md=2),
                dbc.Col([
                    html.P("Price-Only Return (ann.)", className="text-muted mb-0",
                           style={"fontSize": "0.7rem", "textTransform": "uppercase"}),
                    html.H4(f"{price_ann:.2%}", className="mb-0"),
                ], md=2),
            ]),
        ]),
        style={"backgroundColor": "white", "border": "1px solid #4caf50"},
        className="mb-3 mt-2",
    )

    div_section = html.Div([
        html.H5("Total Shareholder Yield — Dividends + Buybacks", className="text-dark mt-4 mb-2"),
        div_impact,
        dbc.Accordion([
            dbc.AccordionItem(div_table, title="Holdings Dividend & Buyback Yields"),
        ], start_collapsed=True, className="mb-2"),
    ])

    # ── Trade log ────────────────────────────────────────────
    trade_section = html.Div()
    log_path = DATA / "trade_log.csv"
    if log_path.exists():
        tlog = pd.read_csv(log_path)
        trade_table = dash_table.DataTable(
            data=tlog.to_dict("records"),
            columns=[{"name": c, "id": c} for c in tlog.columns],
            sort_action="native",
            style_header={
                "backgroundColor": "#f0f0f0", "color": "#212529",
                "fontWeight": "bold", "fontSize": "0.78rem",
                "borderBottom": "2px solid #0d6efd",
            },
            style_cell={
                "backgroundColor": "white", "color": "#212529",
                "fontSize": "0.78rem", "padding": "5px 10px",
                "border": "1px solid #dee2e6",
            },
            page_size=10,
        )
        trade_section = html.Div([
            dbc.Accordion([
                dbc.AccordionItem(trade_table, title="Trade Log"),
            ], start_collapsed=False, className="mt-4 mb-2"),
        ])

    # ━━ Assemble layout ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
    # A holding priced from the last snapshot rather than a live feed must say so
    # on the page. Carrying it silently would overstate how current the numbers
    # are — the position is real, the price simply is not moving any more.
    _stale = d.get("stale_tickers") or []
    stale_banner = None
    if _stale:
        _nm = d["pos_pnl"].set_index("ticker")["name"]
        _labels = ", ".join(f"{_nm.get(t, t)} ({t})" for t in _stale)
        stale_banner = dbc.Alert(
            [
                html.Strong("Stale price:  "),
                f"{_labels} — no live data from the price feed, so the position "
                f"is carried at its last recorded price. Its P&L and weight are "
                f"frozen from that date, and it is excluded from the correlation "
                f"matrix (a constant price has no return series to correlate).",
            ],
            color="warning", className="py-2 mb-3",
            style={"fontSize": "0.85rem"},
        )

    return html.Div([
        stale_banner,
        kpis,

        # Performance + drawdown
        dbc.Row([
            dbc.Col(dcc.Graph(figure=perf_fig, config=CHART_CONFIG), md=12),
        ], className="mb-2"),
        dbc.Row([
            dbc.Col(dcc.Graph(figure=dd_fig, config=CHART_CONFIG), md=12),
        ], className="mb-3"),

        # Exposure pies
        dbc.Row([
            dbc.Col(dcc.Graph(figure=ctry_fig, config=CHART_CONFIG), md=6),
            dbc.Col(dcc.Graph(figure=sec_fig, config=CHART_CONFIG), md=6),
        ], className="mb-3"),

        # Positions table
        dbc.Accordion([
            dbc.AccordionItem(pos_table, title="Holdings"),
        ], start_collapsed=False, className="mb-3"),

        # ── FX / Local return attribution ────────────────────
        html.H5("Return Attribution — Local vs Currency", className="text-dark mt-4 mb-2"),
        _build_fx_section(d),

        # Individual stock chart
        dbc.Row(dbc.Col(
            dcc.Graph(figure=stock_fig, config=CHART_CONFIG),
        ), className="mt-4 mb-3"),

        # Two-column: risk metrics | CAPM
        dbc.Row([
            dbc.Col([
                dbc.Accordion([
                    dbc.AccordionItem(risk_table, title="Risk Metrics"),
                ], start_collapsed=False, className="mb-2"),
            ], md=5),
            dbc.Col(
                dcc.Graph(figure=capm_fig, config=CHART_CONFIG), md=7,
            ),
        ], className="mb-3"),

        # Correlation heatmap
        dbc.Row(dbc.Col(
            dcc.Graph(figure=corr_fig, config=CHART_CONFIG),
        ), className="mb-3"),

        # ── Fama-French 5-Factor Decomposition ───────────────
        _build_ff5_section(d),

        # Fundamentals
        fund_section,

        # Dividends
        div_section,

        # Trade log
        trade_section,

    ]), last_date


# ── Run ───────────────────────────────────────────────────────────
# Warm the cache only when this module is actually serving the dashboard.
# export_markdown.py and eval_app.py both `from dashboard.app import …` for the
# compute helpers; warming on plain import would fire a full yfinance pull as a
# side effect of running a CLI script. Placed at the bottom of the module so the
# worker thread cannot reach build_dashboard_content before it is defined.
_SERVING = (__name__ == "__main__"
            or os.environ.get("SERVER_SOFTWARE", "").startswith("gunicorn")
            or os.environ.get("DASHBOARD_WARM") == "1")
if _SERVING:
    _warm_cache_on_start()

if __name__ == "__main__":
    port = int(os.environ.get("PORT", 8050))
    app.run(debug=False, host="0.0.0.0", port=port)
